name: 'setup-gpg'
description: 'Prepare to get following commits signed'

runs:
    using: composite
    steps:
        - name: Import and load GPG key
          uses: crazy-max/ghaction-import-gpg@v6
          with:
              gpg_private_key: ${{ secrets.GPG_SIGN_KEY }}
              passphrase: ${{ secrets.GPG_PASSPHRASE }}
              git_user_signingkey: true
              git_commit_gpgsign: true
