name: 'manual-git-commit'
description: 'Runs the git command to commit'
inputs:
    branch:
        description: 'Branch where to commit.'
        required: true
        default: ''
    message:
        description: 'Commit message.'
        required: true
        default: ''
    newFiles:
        description: 'Defines if a `git add.` should be made or not.'
        required: false
        default: false

runs:
    using: composite
    steps:
        - name: Add new files (if needed)
          shell: bash
          if: ${{ inputs.newFiles }}
          run: |
              git add .

        - name: Manual git commit
          shell: bash
          run: |
              git commit -m "${{ inputs.message }}"
              git push origin ${{ inputs.branch }}
