#
# This action performs Azure authentication using the Azure CLI.
# It logs in to Azure with the provided subscription, tenant, and client IDs.
#
# HOW TO USE:
#
# To call this reusable action, copy the code between === lines to workflow file,
# uncomment and adjust "uses" as needed (use the latest tag available).
# ======================================================================
# on:
#  pull_request:
#    types: [opened, reopened, labeled, unlabeled]
#
#     (...)
#     steps:
#     (...)
#       - name: Azure Login
#         uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@vVersionHash
#         with:
#           subscription-id: ${{ AZURE_subscription-id }}
#           tenant-id: ${{ AZURE_TENANT_ID }}
#           client-id: ${{ AZURE_CLIENT_ID }}
#
# ======================================================================
#
name: Azure Login
description: 'Logins to Azure using the Azure CLI.'
inputs:
    subscription-id:
        description: 'Azure subscription ID.'
        required: false
        default: ''
    tenant-id:
        description: 'Azure tenant ID.'
        required: false
        default: ''
    client-id:
        description: 'Azure client ID.'
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Azure DevOps Login
          uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@c8485a9aece78d1de3c56451a0a7a2cab0fb3212 #v2.0.9
          with:
              client-id: ${{ inputs.client-id }}
              tenant-id: ${{ inputs.tenant-id }}
              subscription-id: ${{ inputs.subscription-id }}
