# SonarCloud connection settings
sonar.host.url=https://sonarcloud.io
sonar.organization=outsystemsrd

# Required: Unique project key (usually org_repo format)
sonar.projectKey=OutSystems_outsystems-ui

# Project name displayed in SonarCloud
sonar.projectName=OutSystems UI

# Source code location
sonar.sources=src

# Exclude files from analysis (optional)
sonar.exclusions = **/node_modules/**,**/dist/**,**/*.min.js, **/*.spec.ts, **/*.spec.tsx, **/*.stories.tsx, **/*.stories.ts, src/scripts/Utilities/**, **/*DesignTime*, **/*.data.js
sonar.test.exclusions = **/*.spec.ts, **/*.spec.tsx, **/*.stories.tsx, **/*.stories.ts, **/*DesignTime*, **/*.data.js

# JavaScript/TypeScript settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
