#
# This action allows you to get a masked secret from Azure Key Vault using the Azure CLI.
# It implies that the action az-login, is used before this action in the same job as where the secrets will be obtained.
# This action is designed to be reusable and can be called from other workflows.
#
# HOW TO USE:
#
# To call this reusable action, copy the code between === lines to workflow file,
# uncomment and adjust "uses" as needed (use the latest tag available).
# ======================================================================
# on:
#  pull_request:
#    types: [opened, reopened, labeled, unlabeled]
#
#  permissions:
#    id-token: write
#    contents: read
#
#     (...)
#     steps:
#     (...)
#       # First, login to Azure using the az-devops-login action
#       - name: Azure Login
#         uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-devops-login@vVersionHash
#         with:
#           subscription-id: ${{ AZURE_subscription-id }}
#           tenant-id: ${{ AZURE_TENANT_ID }}
#           client-id: ${{ AZURE_CLIENT_ID }}
#
#       # Then, multiple calls to the az-keyvault-get action can be made to retrieve different secrets
#       # from the Azure Key Vault. The secrets will be masked in the logs.
#
#       - name: Get KeyVault Secret 1
#         id: GetAzKeyVaultSecret_1
#         uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@vVersionHash
#         with:
#           keyvault-name: ${{ AZURE_KEYVAULT_NAME }}
#           key-name: ${{ AZURE_KEYVAULT_SECRET_NAME_1 }}
#
#       - name: Get KeyVault Secret 2
#         id: GetAzKeyVaultSecret_2
#         uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@vVersionHash
#         with:
#           keyvault-name: ${{ AZURE_KEYVAULT_NAME }}
#           key-name: ${{ AZURE_KEYVAULT_SECRET_NAME_2 }}
#
#       - name: Use KeyVault Secrets
#         run: |
#           echo "The secret 1 value is: ${{ steps.GetAzKeyVaultSecret_1.outputs.az-keyvault-value }}"
#           echo "The secret 2 value is: ${{ steps.GetAzKeyVaultSecret_2.outputs.az-keyvault-value }}"
#
# ======================================================================
#
name: Azure KeyVault Get Value
description: 'Get a secret from Azure Key Vault.'
inputs:
    keyvault-name:
        description: 'Name of the Azure Key Vault.'
        required: false
        default: 'kv-ui-components'
    key-name:
        description: 'Name of the secret to retrieve.'
        required: true
        default: ''
outputs:
    az-keyvault-value:
        description: 'The Azure key value.'
        value: ${{ steps.GetAzKeyVaultSecret.outputs.az-keyvault-secret }}

runs:
    using: composite
    steps:
        - name: Azure KeyVault get Value
          uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
          id: GetAzKeyVaultSecret
          with:
              inlineScript: |
                  secretValue=$(az keyvault secret show --name "${{ inputs.key-name }}" --vault-name "${{ inputs.keyvault-name }}" --query "value" --output tsv)
                  echo "::add-mask::$secretValue"
                  echo "az-keyvault-secret=$secretValue" >> $GITHUB_OUTPUT
