import type { Meta, StoryObj } from '@storybook/html-vite';
import { renderStatic } from '../_helpers/osui';

/**
 * Upload — the OutSystems platform **widget**, transcribed to static markup
 * (see Widgets/Button for why the Widgets group is static; ADR-0009).
 *
 * Captured from @outsystems/runtime-widgets-js@6.25.4 under React 17 with
 * `accept: 0` (Image):
 *   `span.upload-file` > `label[data-upload][tabindex=0]`
 *                          > `input[type=file][accept="image/*"]` (display:none)
 *
 * The label has **no text content** — everything visible is generated by the
 * platform base layer's pseudo-elements on `[data-upload]`
 * (.storybook/platform/platform-core.css), which is exactly why that layer has
 * to be vendored for this story to mean anything. `accept` maps 0→`image/*`,
 * 1→`video/*`, 2→omitted.
 *
 * CSS contract: src/scss/03-widgets/_upload.scss (plus the `.upload-file
 * span.validation-message` rule in _form.scss).
 */
const meta: Meta = { title: 'Widgets/Upload' };
export default meta;
type Story = StoryObj;

export const Default: Story = {
	render: () =>
		renderStatic(`
			<span class="upload-file">
				<label data-upload="" class="" tabindex="0">
					<input type="file" accept="image/*" style="display: none;">
				</label>
			</span>`),
};
