import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

import { loadSnapshots, validateSnapshot } from '../scripts/ai-docs/lib/snapshot.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docsAi = path.join(root, 'docs-ai');
const manifests = fs.readdirSync(docsAi).filter((f) => f.endsWith('.json'));

test('every $schema reference of a docs-ai manifest resolves to a committed schema file', () => {
	for (const file of manifests) {
		const { $schema } = JSON.parse(fs.readFileSync(path.join(docsAi, file), 'utf8'));
		// the blocks, enums and icons manifests ship without a schema; the ones that name one must resolve
		if ($schema) assert.ok(fs.existsSync(path.join(docsAi, $schema)), `${file}: ${$schema} does not exist`);
	}
});

test('every generated file names a generator that exists on this branch', () => {
	const sources = new Set();
	for (const file of manifests) {
		const { source } = JSON.parse(fs.readFileSync(path.join(docsAi, file), 'utf8'));
		if (source) sources.add(source);
	}
	for (const file of fs.readdirSync(path.join(docsAi, 'schema', 'configs'))) {
		const { description } = JSON.parse(fs.readFileSync(path.join(docsAi, 'schema', 'configs', file), 'utf8'));
		const m = description.match(/Generated by (\S+)\./);
		assert.ok(m, `${file}: no "Generated by" sentence`);
		sources.add(m[1]);
	}
	const types = fs.readFileSync(path.join(root, 'src/scripts/OutSystems/OSUI/Patterns/PatternTypes.ts'), 'utf8');
	for (const m of types.matchAll(/via (scripts\/\S+\.mjs)|by (scripts\/\S+\.mjs)/g)) sources.add(m[1] ?? m[2]);
	assert.ok(sources.size > 0);
	for (const source of sources) assert.ok(fs.existsSync(path.join(root, source)), `${source} does not exist`);
});

test('registry.json carries only what the inventory cannot derive', async () => {
	const { buildInventory } = await import('../scripts/ai-docs/lib/inventory.mjs');
	const inv = buildInventory(root);
	const defaults = new Map(inv.cssComponents.map((c) => [c.name, c.defaultKind]));
	for (const p of inv.patterns) defaults.set(p.name, 'pattern');
	const registry = JSON.parse(fs.readFileSync(path.join(root, 'scripts/ai-docs/registry.json'), 'utf8'));
	const allowed = new Set(['kind', 'title', 'host', 'story', 'block']);
	for (const [name, entry] of Object.entries(registry.components)) {
		assert.ok(Object.keys(entry).length > 0, `${name}: empty entry`);
		for (const field of Object.keys(entry)) assert.ok(allowed.has(field), `${name}: unread field ${field}`);
		// block-linked entries keep their kind: blockRuntimeOf reads it to tell a pattern from a stylesheet
		if (entry.block) assert.ok(entry.kind, `${name}: a block-linked entry needs its kind`);
		else if (entry.kind) assert.notEqual(entry.kind, defaults.get(name), `${name}: kind only restates the default`);
	}
});

test('llms.txt carries the platform context and every runtime name in the catalogue resolves', async () => {
	const { DOCS_BASE, PATTERN_PAGES } = await import('../scripts/ai-docs/lib/platform-docs.mjs');
	const index = fs.readFileSync(path.join(docsAi, 'llms.txt'), 'utf8');
	assert.ok(index.includes('llms-platform.txt'), 'llms.txt must point at the platform tier');
	const platform = fs.readFileSync(path.join(docsAi, 'llms-platform.txt'), 'utf8');
	assert.ok(platform.includes('## Concept pages') && platform.includes('## Pattern catalogue'));
	assert.doesNotMatch(platform, /→ [^·\n]*\?/, 'a catalogue entry names a runtime component that does not exist');
	for (const m of platform.matchAll(/https?:\/\/\S+/g)) assert.ok(m[0].startsWith(DOCS_BASE), m[0]);
	const slugs = Object.values(PATTERN_PAGES).flatMap((g) => Object.values(g).map((p) => p.slug));
	assert.equal(new Set(slugs).size, slugs.length, 'duplicate documentation slug');
	const known = new Set(slugs);
	for (const file of ['llms-components.txt', 'llms-patterns.txt']) {
		const text = fs.readFileSync(path.join(docsAi, file), 'utf8');
		for (const m of text.matchAll(/^Docs: (.+)$/gm)) for (const slug of m[1].split(' · ')) assert.ok(known.has(slug), `${file}: ${slug}`);
	}
});

test('the committed block snapshot validates against its schema', () => {
	const snapshots = loadSnapshots();
	assert.ok(snapshots.length >= 1, 'no snapshot under scripts/ai-docs/snapshot');
	for (const s of snapshots) {
		assert.deepEqual(validateSnapshot(s), [], `${path.basename(s.file)} violates osui.blocks.schema.json`);
		assert.ok(s.source.origin.sha256, 'origin.sha256 pins the exported OML');
	}
});
