name: 'signed-gpg-commit'
description: 'Prepare and sign the commit signed'
inputs:
    branch:
        description: 'Branch where to commit.'
        required: true
        default: ''
    message:
        description: 'Commit message.'
        required: true
        default: ''
    newFiles:
        description: 'Defines if a `git add.` should be made or not.'
        required: false
        default: false

runs:
    using: composite
    steps:
        - name: Setup GPG to sign commits
          uses: ./.github/os-git-actions/setup-gpg/

        - name: Perform git commit
          uses: ./.github/os-git-actions/manual-commit/
          with:
              branch: ${{ inputs.branch }}
              message: ${{ inputs.message }}
              newFiles: ${{ inputs.newFiles }}
