// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace Providers.Dropdown.VirtualSelect {
	/*
	 * List of all available library options.
	 **/
	export const options = {
		ele: undefined,
		dropboxWrapper: undefined,
		options: undefined,
		valueKey: undefined,
		labelKey: undefined,
		descriptionKey: undefined,
		aliasKey: undefined,
		disabledOptions: undefined,
		multiple: undefined,
		search: undefined,
		searchByStartsWith: undefined,
		searchGroup: undefined,
		disabled: undefined,
		required: undefined,
		autofocus: undefined,
		hideClearButton: undefined,
		autoSelectFirstOption: undefined,
		hasOptionDescription: undefined,
		disableSelectAll: undefined,
		optionsCount: undefined,
		optionHeight: undefined,
		position: undefined,
		textDirection: undefined,
		selectedValue: undefined,
		silentInitialValueSet: undefined,
		dropboxWidth: undefined,
		zIndex: undefined,
		noOfDisplayValues: undefined,
		allowNewOption: undefined,
		tooltipFontSize: undefined,
		tooltipAlignment: undefined,
		tooltipMaxWidth: undefined,
		showSelectedOptionsFirst: undefined,
		markSearchResults: undefined,
		name: undefined,
		keepAlwaysOpen: undefined,
		maxValues: undefined,
		additionalClasses: undefined,
		showDropboxAsPopup: undefined,
		popupDropboxBreakpoint: undefined,
		popupPosition: undefined,
		onServerSearch: undefined,
		labelRenderer: undefined,
		ariaLabelledby: undefined,
		hideValueTooltipOnSelectAll: undefined,
		showOptionsOnlyOnSearch: undefined,
		selectAllOnlyVisible: undefined,
		alwaysShowSelectedOptionsCount: undefined,
		disableAllOptionsSelectedText: undefined,
		showValueAsTags: undefined,
		disableOptionGroupCheckbox: undefined,
		enableSecureText: undefined,
		setValueAsArray: undefined,
		emptyValue: undefined,
		disableValidation: undefined,
		useGroupValue: undefined,
		maxWidth: undefined,
		updatePositionThrottle: undefined,
		placeholder: undefined,
		noOptionsText: undefined,
		noSearchResultsText: undefined,
		selectAllText: undefined,
		searchPlaceholderText: undefined,
		optionsSelectedText: undefined,
		optionSelectedText: undefined,
		allOptionsSelectedText: undefined,
		clearButtonText: undefined,
		moreText: undefined,
	};
}
