// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Regenerate: npm run docs:tokens (requires npm run build:tokens first)
export const Border = [
    {
        "token": "border.size.0",
        "css_variable": "--token-border-size-0",
        "utility_class": ".token-border-size-0",
        "value": "0px"
    },
    {
        "token": "border.size.025",
        "css_variable": "--token-border-size-025",
        "utility_class": ".token-border-size-025",
        "value": "1px"
    },
    {
        "token": "border.size.050",
        "css_variable": "--token-border-size-050",
        "utility_class": ".token-border-size-050",
        "value": "2px"
    },
    {
        "token": "border.size.075",
        "css_variable": "--token-border-size-075",
        "utility_class": ".token-border-size-075",
        "value": "3px"
    }
];

export const BorderStyle = [];

export const BorderRadius = [
    {
        "token": "border.radius.0",
        "css_variable": "--token-border-radius-0",
        "utility_class": ".token-border-radius-0",
        "value": "0px"
    },
    {
        "token": "border.radius.025",
        "css_variable": "--token-border-radius-025",
        "utility_class": ".token-border-radius-025",
        "value": "2px"
    },
    {
        "token": "border.radius.100",
        "css_variable": "--token-border-radius-100",
        "utility_class": ".token-border-radius-100",
        "value": "4px"
    },
    {
        "token": "border.radius.1000",
        "css_variable": "--token-border-radius-1000",
        "utility_class": ".token-border-radius-1000",
        "value": "40px"
    },
    {
        "token": "border.radius.200",
        "css_variable": "--token-border-radius-200",
        "utility_class": ".token-border-radius-200",
        "value": "8px"
    },
    {
        "token": "border.radius.300",
        "css_variable": "--token-border-radius-300",
        "utility_class": ".token-border-radius-300",
        "value": "12px"
    },
    {
        "token": "border.radius.400",
        "css_variable": "--token-border-radius-400",
        "utility_class": ".token-border-radius-400",
        "value": "16px"
    },
    {
        "token": "border.radius.500",
        "css_variable": "--token-border-radius-500",
        "utility_class": ".token-border-radius-500",
        "value": "20px"
    },
    {
        "token": "border.radius.800",
        "css_variable": "--token-border-radius-800",
        "utility_class": ".token-border-radius-800",
        "value": "32px"
    },
    {
        "token": "border.radius.full",
        "css_variable": "--token-border-radius-full",
        "utility_class": ".token-border-radius-full",
        "value": "999px"
    }
];
