// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Regenerate: npm run docs:tokens (requires npm run build:tokens first)
export const Elevation = [
    {
        "token": "elevation.1",
        "css_variable": "--token-elevation-1",
        "utility_class": ".token-elevation-1",
        "value": "0px 3px 9px 0px rgba(0, 0, 0, 0.07), 0px 0px 4px 0px rgba(0, 0, 0, 0.04)",
        "usage": "Used for foundational components like cards to create a subtle lift from the background."
    },
    {
        "token": "elevation.2",
        "css_variable": "--token-elevation-2",
        "utility_class": ".token-elevation-2",
        "value": "0px 8px 25px 0px rgba(0, 0, 0, 0.08), 0px 1px 5px 0px rgba(0, 0, 0, 0.05)",
        "usage": "Ideal for interactive elements such as top bar, tooltips, and layered components that appear on hover or click."
    },
    {
        "token": "elevation.3",
        "css_variable": "--token-elevation-3",
        "utility_class": ".token-elevation-3",
        "value": "0px 6px 32px 0px rgba(0, 0, 0, 0.16), 0px 2px 7px 0px rgba(0, 0, 0, 0.05)",
        "usage": "Reserved for components that provide feedback like bottom sheet or toasts, or secondary navigational elements."
    },
    {
        "token": "elevation.4",
        "css_variable": "--token-elevation-4",
        "utility_class": ".token-elevation-4",
        "value": "0px 15px 48px 0px rgba(0, 0, 0, 0.18), 0px 3px 12px 0px rgba(0, 0, 0, 0.12)",
        "usage": "The highest elevation, designed for high-priority and interruptive elements such as modals and side menus that appear over all other content."
    }
];

export const ZIndex = [
    {
        "token": "z.index.0",
        "css_variable": "--token-z-index-0",
        "utility_class": ".token-z-index-0",
        "value": "0",
        "usage": "Base level z-index for elements that should be at the default stacking level."
    },
    {
        "token": "z.index.100",
        "css_variable": "--token-z-index-100",
        "utility_class": ".token-z-index-100",
        "value": "100",
        "usage": "Low priority layering for subtle UI elements."
    },
    {
        "token": "z.index.200",
        "css_variable": "--token-z-index-200",
        "utility_class": ".token-z-index-200",
        "value": "200",
        "usage": "Standard layering for components like dropdowns and popovers."
    },
    {
        "token": "z.index.300",
        "css_variable": "--token-z-index-300",
        "utility_class": ".token-z-index-300",
        "value": "300",
        "usage": "Medium priority layering for components like fixed headers or sticky elements."
    },
    {
        "token": "z.index.400",
        "css_variable": "--token-z-index-400",
        "utility_class": ".token-z-index-400",
        "value": "400",
        "usage": "High priority layering for important overlays like bottom sheets or side menus."
    },
    {
        "token": "z.index.500",
        "css_variable": "--token-z-index-500",
        "utility_class": ".token-z-index-500",
        "value": "500",
        "usage": "Highest standard priority layering for critical modals and dialogs."
    },
    {
        "token": "z.index.bottom",
        "css_variable": "--token-z-index-bottom",
        "utility_class": ".token-z-index-bottom",
        "value": "-99999",
        "usage": "Forces an element to appear below all other content on the page."
    },
    {
        "token": "z.index.top",
        "css_variable": "--token-z-index-top",
        "utility_class": ".token-z-index-top",
        "value": "99999",
        "usage": "Forces an element to appear above all other content on the page."
    }
];
