// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Regenerate: npm run docs:tokens (requires npm run build:tokens first)
export const Spacing = [
    {
        "token": "space.0",
        "css_variable": "--token-space-0",
        "utility_class": ".token-space-0",
        "value": "0px"
    },
    {
        "token": "space.050",
        "css_variable": "--token-space-050",
        "utility_class": ".token-space-050",
        "value": "2px"
    },
    {
        "token": "space.100",
        "css_variable": "--token-space-100",
        "utility_class": ".token-space-100",
        "value": "4px"
    },
    {
        "token": "space.150",
        "css_variable": "--token-space-150",
        "utility_class": ".token-space-150",
        "value": "6px"
    },
    {
        "token": "space.200",
        "css_variable": "--token-space-200",
        "utility_class": ".token-space-200",
        "value": "8px"
    },
    {
        "token": "space.250",
        "css_variable": "--token-space-250",
        "utility_class": ".token-space-250",
        "value": "10px"
    },
    {
        "token": "space.300",
        "css_variable": "--token-space-300",
        "utility_class": ".token-space-300",
        "value": "12px"
    },
    {
        "token": "space.400",
        "css_variable": "--token-space-400",
        "utility_class": ".token-space-400",
        "value": "16px"
    },
    {
        "token": "space.500",
        "css_variable": "--token-space-500",
        "utility_class": ".token-space-500",
        "value": "20px"
    },
    {
        "token": "space.600",
        "css_variable": "--token-space-600",
        "utility_class": ".token-space-600",
        "value": "24px"
    },
    {
        "token": "space.700",
        "css_variable": "--token-space-700",
        "utility_class": ".token-space-700",
        "value": "28px"
    },
    {
        "token": "space.800",
        "css_variable": "--token-space-800",
        "utility_class": ".token-space-800",
        "value": "32px"
    },
    {
        "token": "space.900",
        "css_variable": "--token-space-900",
        "utility_class": ".token-space-900",
        "value": "36px"
    },
    {
        "token": "space.1000",
        "css_variable": "--token-space-1000",
        "utility_class": ".token-space-1000",
        "value": "40px"
    },
    {
        "token": "space.1100",
        "css_variable": "--token-space-1100",
        "utility_class": ".token-space-1100",
        "value": "44px"
    },
    {
        "token": "space.1200",
        "css_variable": "--token-space-1200",
        "utility_class": ".token-space-1200",
        "value": "48px"
    },
    {
        "token": "space.1400",
        "css_variable": "--token-space-1400",
        "utility_class": ".token-space-1400",
        "value": "56px"
    },
    {
        "token": "space.1600",
        "css_variable": "--token-space-1600",
        "utility_class": ".token-space-1600",
        "value": "64px"
    },
    {
        "token": "space.1800",
        "css_variable": "--token-space-1800",
        "utility_class": ".token-space-1800",
        "value": "72px"
    },
    {
        "token": "space.2000",
        "css_variable": "--token-space-2000",
        "utility_class": ".token-space-2000",
        "value": "80px"
    },
    {
        "token": "space.2400",
        "css_variable": "--token-space-2400",
        "utility_class": ".token-space-2400",
        "value": "96px"
    },
    {
        "token": "space.2800",
        "css_variable": "--token-space-2800",
        "utility_class": ".token-space-2800",
        "value": "112px"
    },
    {
        "token": "space.3200",
        "css_variable": "--token-space-3200",
        "utility_class": ".token-space-3200",
        "value": "128px"
    },
    {
        "token": "space.3400",
        "css_variable": "--token-space-3400",
        "utility_class": ".token-space-3400",
        "value": "136px"
    },
    {
        "token": "space.3600",
        "css_variable": "--token-space-3600",
        "utility_class": ".token-space-3600",
        "value": "144px"
    },
    {
        "token": "space.4000",
        "css_variable": "--token-space-4000",
        "utility_class": ".token-space-4000",
        "value": "160px"
    },
    {
        "token": "space.5000",
        "css_variable": "--token-space-5000",
        "utility_class": ".token-space-5000",
        "value": "200px"
    },
    {
        "token": "space.6200",
        "css_variable": "--token-space-6200",
        "utility_class": ".token-space-6200",
        "value": "248px"
    },
    {
        "token": "space.7400",
        "css_variable": "--token-space-7400",
        "utility_class": ".token-space-7400",
        "value": "296px"
    },
    {
        "token": "space.9000",
        "css_variable": "--token-space-9000",
        "utility_class": ".token-space-9000",
        "value": "360px"
    }
];

export const Margin = [
    {
        "utility_class": ".token-margin-0",
        "value": "0px",
        "usage": "Apply 0px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-0",
        "value": "0px",
        "usage": "Apply 0px margin to top"
    },
    {
        "utility_class": ".token-margin-end-0",
        "value": "0px",
        "usage": "Apply 0px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-0",
        "value": "0px",
        "usage": "Apply 0px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-0",
        "value": "0px",
        "usage": "Apply 0px margin to start"
    },
    {
        "utility_class": ".token-margin-050",
        "value": "2px",
        "usage": "Apply 2px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-050",
        "value": "2px",
        "usage": "Apply 2px margin to top"
    },
    {
        "utility_class": ".token-margin-end-050",
        "value": "2px",
        "usage": "Apply 2px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-050",
        "value": "2px",
        "usage": "Apply 2px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-050",
        "value": "2px",
        "usage": "Apply 2px margin to start"
    },
    {
        "utility_class": ".token-margin-100",
        "value": "4px",
        "usage": "Apply 4px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-100",
        "value": "4px",
        "usage": "Apply 4px margin to top"
    },
    {
        "utility_class": ".token-margin-end-100",
        "value": "4px",
        "usage": "Apply 4px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-100",
        "value": "4px",
        "usage": "Apply 4px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-100",
        "value": "4px",
        "usage": "Apply 4px margin to start"
    },
    {
        "utility_class": ".token-margin-150",
        "value": "6px",
        "usage": "Apply 6px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-150",
        "value": "6px",
        "usage": "Apply 6px margin to top"
    },
    {
        "utility_class": ".token-margin-end-150",
        "value": "6px",
        "usage": "Apply 6px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-150",
        "value": "6px",
        "usage": "Apply 6px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-150",
        "value": "6px",
        "usage": "Apply 6px margin to start"
    },
    {
        "utility_class": ".token-margin-200",
        "value": "8px",
        "usage": "Apply 8px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-200",
        "value": "8px",
        "usage": "Apply 8px margin to top"
    },
    {
        "utility_class": ".token-margin-end-200",
        "value": "8px",
        "usage": "Apply 8px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-200",
        "value": "8px",
        "usage": "Apply 8px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-200",
        "value": "8px",
        "usage": "Apply 8px margin to start"
    },
    {
        "utility_class": ".token-margin-250",
        "value": "10px",
        "usage": "Apply 10px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-250",
        "value": "10px",
        "usage": "Apply 10px margin to top"
    },
    {
        "utility_class": ".token-margin-end-250",
        "value": "10px",
        "usage": "Apply 10px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-250",
        "value": "10px",
        "usage": "Apply 10px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-250",
        "value": "10px",
        "usage": "Apply 10px margin to start"
    },
    {
        "utility_class": ".token-margin-300",
        "value": "12px",
        "usage": "Apply 12px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-300",
        "value": "12px",
        "usage": "Apply 12px margin to top"
    },
    {
        "utility_class": ".token-margin-end-300",
        "value": "12px",
        "usage": "Apply 12px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-300",
        "value": "12px",
        "usage": "Apply 12px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-300",
        "value": "12px",
        "usage": "Apply 12px margin to start"
    },
    {
        "utility_class": ".token-margin-400",
        "value": "16px",
        "usage": "Apply 16px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-400",
        "value": "16px",
        "usage": "Apply 16px margin to top"
    },
    {
        "utility_class": ".token-margin-end-400",
        "value": "16px",
        "usage": "Apply 16px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-400",
        "value": "16px",
        "usage": "Apply 16px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-400",
        "value": "16px",
        "usage": "Apply 16px margin to start"
    },
    {
        "utility_class": ".token-margin-500",
        "value": "20px",
        "usage": "Apply 20px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-500",
        "value": "20px",
        "usage": "Apply 20px margin to top"
    },
    {
        "utility_class": ".token-margin-end-500",
        "value": "20px",
        "usage": "Apply 20px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-500",
        "value": "20px",
        "usage": "Apply 20px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-500",
        "value": "20px",
        "usage": "Apply 20px margin to start"
    },
    {
        "utility_class": ".token-margin-600",
        "value": "24px",
        "usage": "Apply 24px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-600",
        "value": "24px",
        "usage": "Apply 24px margin to top"
    },
    {
        "utility_class": ".token-margin-end-600",
        "value": "24px",
        "usage": "Apply 24px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-600",
        "value": "24px",
        "usage": "Apply 24px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-600",
        "value": "24px",
        "usage": "Apply 24px margin to start"
    },
    {
        "utility_class": ".token-margin-700",
        "value": "28px",
        "usage": "Apply 28px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-700",
        "value": "28px",
        "usage": "Apply 28px margin to top"
    },
    {
        "utility_class": ".token-margin-end-700",
        "value": "28px",
        "usage": "Apply 28px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-700",
        "value": "28px",
        "usage": "Apply 28px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-700",
        "value": "28px",
        "usage": "Apply 28px margin to start"
    },
    {
        "utility_class": ".token-margin-800",
        "value": "32px",
        "usage": "Apply 32px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-800",
        "value": "32px",
        "usage": "Apply 32px margin to top"
    },
    {
        "utility_class": ".token-margin-end-800",
        "value": "32px",
        "usage": "Apply 32px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-800",
        "value": "32px",
        "usage": "Apply 32px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-800",
        "value": "32px",
        "usage": "Apply 32px margin to start"
    },
    {
        "utility_class": ".token-margin-900",
        "value": "36px",
        "usage": "Apply 36px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-900",
        "value": "36px",
        "usage": "Apply 36px margin to top"
    },
    {
        "utility_class": ".token-margin-end-900",
        "value": "36px",
        "usage": "Apply 36px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-900",
        "value": "36px",
        "usage": "Apply 36px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-900",
        "value": "36px",
        "usage": "Apply 36px margin to start"
    },
    {
        "utility_class": ".token-margin-1000",
        "value": "40px",
        "usage": "Apply 40px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1000",
        "value": "40px",
        "usage": "Apply 40px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1000",
        "value": "40px",
        "usage": "Apply 40px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1000",
        "value": "40px",
        "usage": "Apply 40px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1000",
        "value": "40px",
        "usage": "Apply 40px margin to start"
    },
    {
        "utility_class": ".token-margin-1100",
        "value": "44px",
        "usage": "Apply 44px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1100",
        "value": "44px",
        "usage": "Apply 44px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1100",
        "value": "44px",
        "usage": "Apply 44px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1100",
        "value": "44px",
        "usage": "Apply 44px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1100",
        "value": "44px",
        "usage": "Apply 44px margin to start"
    },
    {
        "utility_class": ".token-margin-1200",
        "value": "48px",
        "usage": "Apply 48px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1200",
        "value": "48px",
        "usage": "Apply 48px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1200",
        "value": "48px",
        "usage": "Apply 48px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1200",
        "value": "48px",
        "usage": "Apply 48px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1200",
        "value": "48px",
        "usage": "Apply 48px margin to start"
    },
    {
        "utility_class": ".token-margin-1400",
        "value": "56px",
        "usage": "Apply 56px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1400",
        "value": "56px",
        "usage": "Apply 56px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1400",
        "value": "56px",
        "usage": "Apply 56px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1400",
        "value": "56px",
        "usage": "Apply 56px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1400",
        "value": "56px",
        "usage": "Apply 56px margin to start"
    },
    {
        "utility_class": ".token-margin-1600",
        "value": "64px",
        "usage": "Apply 64px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1600",
        "value": "64px",
        "usage": "Apply 64px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1600",
        "value": "64px",
        "usage": "Apply 64px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1600",
        "value": "64px",
        "usage": "Apply 64px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1600",
        "value": "64px",
        "usage": "Apply 64px margin to start"
    },
    {
        "utility_class": ".token-margin-1800",
        "value": "72px",
        "usage": "Apply 72px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-1800",
        "value": "72px",
        "usage": "Apply 72px margin to top"
    },
    {
        "utility_class": ".token-margin-end-1800",
        "value": "72px",
        "usage": "Apply 72px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-1800",
        "value": "72px",
        "usage": "Apply 72px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-1800",
        "value": "72px",
        "usage": "Apply 72px margin to start"
    },
    {
        "utility_class": ".token-margin-2000",
        "value": "80px",
        "usage": "Apply 80px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-2000",
        "value": "80px",
        "usage": "Apply 80px margin to top"
    },
    {
        "utility_class": ".token-margin-end-2000",
        "value": "80px",
        "usage": "Apply 80px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-2000",
        "value": "80px",
        "usage": "Apply 80px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-2000",
        "value": "80px",
        "usage": "Apply 80px margin to start"
    },
    {
        "utility_class": ".token-margin-2400",
        "value": "96px",
        "usage": "Apply 96px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-2400",
        "value": "96px",
        "usage": "Apply 96px margin to top"
    },
    {
        "utility_class": ".token-margin-end-2400",
        "value": "96px",
        "usage": "Apply 96px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-2400",
        "value": "96px",
        "usage": "Apply 96px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-2400",
        "value": "96px",
        "usage": "Apply 96px margin to start"
    },
    {
        "utility_class": ".token-margin-2800",
        "value": "112px",
        "usage": "Apply 112px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-2800",
        "value": "112px",
        "usage": "Apply 112px margin to top"
    },
    {
        "utility_class": ".token-margin-end-2800",
        "value": "112px",
        "usage": "Apply 112px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-2800",
        "value": "112px",
        "usage": "Apply 112px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-2800",
        "value": "112px",
        "usage": "Apply 112px margin to start"
    },
    {
        "utility_class": ".token-margin-3200",
        "value": "128px",
        "usage": "Apply 128px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-3200",
        "value": "128px",
        "usage": "Apply 128px margin to top"
    },
    {
        "utility_class": ".token-margin-end-3200",
        "value": "128px",
        "usage": "Apply 128px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-3200",
        "value": "128px",
        "usage": "Apply 128px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-3200",
        "value": "128px",
        "usage": "Apply 128px margin to start"
    },
    {
        "utility_class": ".token-margin-3400",
        "value": "136px",
        "usage": "Apply 136px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-3400",
        "value": "136px",
        "usage": "Apply 136px margin to top"
    },
    {
        "utility_class": ".token-margin-end-3400",
        "value": "136px",
        "usage": "Apply 136px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-3400",
        "value": "136px",
        "usage": "Apply 136px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-3400",
        "value": "136px",
        "usage": "Apply 136px margin to start"
    },
    {
        "utility_class": ".token-margin-3600",
        "value": "144px",
        "usage": "Apply 144px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-3600",
        "value": "144px",
        "usage": "Apply 144px margin to top"
    },
    {
        "utility_class": ".token-margin-end-3600",
        "value": "144px",
        "usage": "Apply 144px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-3600",
        "value": "144px",
        "usage": "Apply 144px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-3600",
        "value": "144px",
        "usage": "Apply 144px margin to start"
    },
    {
        "utility_class": ".token-margin-4000",
        "value": "160px",
        "usage": "Apply 160px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-4000",
        "value": "160px",
        "usage": "Apply 160px margin to top"
    },
    {
        "utility_class": ".token-margin-end-4000",
        "value": "160px",
        "usage": "Apply 160px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-4000",
        "value": "160px",
        "usage": "Apply 160px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-4000",
        "value": "160px",
        "usage": "Apply 160px margin to start"
    },
    {
        "utility_class": ".token-margin-5000",
        "value": "200px",
        "usage": "Apply 200px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-5000",
        "value": "200px",
        "usage": "Apply 200px margin to top"
    },
    {
        "utility_class": ".token-margin-end-5000",
        "value": "200px",
        "usage": "Apply 200px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-5000",
        "value": "200px",
        "usage": "Apply 200px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-5000",
        "value": "200px",
        "usage": "Apply 200px margin to start"
    },
    {
        "utility_class": ".token-margin-6200",
        "value": "248px",
        "usage": "Apply 248px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-6200",
        "value": "248px",
        "usage": "Apply 248px margin to top"
    },
    {
        "utility_class": ".token-margin-end-6200",
        "value": "248px",
        "usage": "Apply 248px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-6200",
        "value": "248px",
        "usage": "Apply 248px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-6200",
        "value": "248px",
        "usage": "Apply 248px margin to start"
    },
    {
        "utility_class": ".token-margin-7400",
        "value": "296px",
        "usage": "Apply 296px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-7400",
        "value": "296px",
        "usage": "Apply 296px margin to top"
    },
    {
        "utility_class": ".token-margin-end-7400",
        "value": "296px",
        "usage": "Apply 296px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-7400",
        "value": "296px",
        "usage": "Apply 296px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-7400",
        "value": "296px",
        "usage": "Apply 296px margin to start"
    },
    {
        "utility_class": ".token-margin-9000",
        "value": "360px",
        "usage": "Apply 360px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top-9000",
        "value": "360px",
        "usage": "Apply 360px margin to top"
    },
    {
        "utility_class": ".token-margin-end-9000",
        "value": "360px",
        "usage": "Apply 360px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom-9000",
        "value": "360px",
        "usage": "Apply 360px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start-9000",
        "value": "360px",
        "usage": "Apply 360px margin to start"
    },
    {
        "utility_class": ".token-margin",
        "value": "16px",
        "usage": "Apply 16px margin to all sides"
    },
    {
        "utility_class": ".token-margin-top",
        "value": "16px",
        "usage": "Apply 16px margin to top"
    },
    {
        "utility_class": ".token-margin-end",
        "value": "16px",
        "usage": "Apply 16px margin to end"
    },
    {
        "utility_class": ".token-margin-bottom",
        "value": "16px",
        "usage": "Apply 16px margin to bottom"
    },
    {
        "utility_class": ".token-margin-start",
        "value": "16px",
        "usage": "Apply 16px margin to start"
    },
    {
        "utility_class": ".token-margin-vertical",
        "value": "16px",
        "usage": "Apply 16px margin to top and bottom"
    },
    {
        "utility_class": ".token-margin-horizontal",
        "value": "16px",
        "usage": "Apply 16px margin to start and end"
    },
    {
        "utility_class": ".token-no-margin",
        "value": "0px",
        "usage": "Apply 0px margin to all sides"
    }
];

export const Padding = [
    {
        "utility_class": ".token-padding-0",
        "value": "0px",
        "usage": "Apply 0px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-0",
        "value": "0px",
        "usage": "Apply 0px padding to top"
    },
    {
        "utility_class": ".token-padding-end-0",
        "value": "0px",
        "usage": "Apply 0px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-0",
        "value": "0px",
        "usage": "Apply 0px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-0",
        "value": "0px",
        "usage": "Apply 0px padding to start"
    },
    {
        "utility_class": ".token-padding-050",
        "value": "2px",
        "usage": "Apply 2px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-050",
        "value": "2px",
        "usage": "Apply 2px padding to top"
    },
    {
        "utility_class": ".token-padding-end-050",
        "value": "2px",
        "usage": "Apply 2px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-050",
        "value": "2px",
        "usage": "Apply 2px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-050",
        "value": "2px",
        "usage": "Apply 2px padding to start"
    },
    {
        "utility_class": ".token-padding-100",
        "value": "4px",
        "usage": "Apply 4px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-100",
        "value": "4px",
        "usage": "Apply 4px padding to top"
    },
    {
        "utility_class": ".token-padding-end-100",
        "value": "4px",
        "usage": "Apply 4px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-100",
        "value": "4px",
        "usage": "Apply 4px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-100",
        "value": "4px",
        "usage": "Apply 4px padding to start"
    },
    {
        "utility_class": ".token-padding-150",
        "value": "6px",
        "usage": "Apply 6px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-150",
        "value": "6px",
        "usage": "Apply 6px padding to top"
    },
    {
        "utility_class": ".token-padding-end-150",
        "value": "6px",
        "usage": "Apply 6px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-150",
        "value": "6px",
        "usage": "Apply 6px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-150",
        "value": "6px",
        "usage": "Apply 6px padding to start"
    },
    {
        "utility_class": ".token-padding-200",
        "value": "8px",
        "usage": "Apply 8px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-200",
        "value": "8px",
        "usage": "Apply 8px padding to top"
    },
    {
        "utility_class": ".token-padding-end-200",
        "value": "8px",
        "usage": "Apply 8px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-200",
        "value": "8px",
        "usage": "Apply 8px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-200",
        "value": "8px",
        "usage": "Apply 8px padding to start"
    },
    {
        "utility_class": ".token-padding-250",
        "value": "10px",
        "usage": "Apply 10px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-250",
        "value": "10px",
        "usage": "Apply 10px padding to top"
    },
    {
        "utility_class": ".token-padding-end-250",
        "value": "10px",
        "usage": "Apply 10px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-250",
        "value": "10px",
        "usage": "Apply 10px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-250",
        "value": "10px",
        "usage": "Apply 10px padding to start"
    },
    {
        "utility_class": ".token-padding-300",
        "value": "12px",
        "usage": "Apply 12px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-300",
        "value": "12px",
        "usage": "Apply 12px padding to top"
    },
    {
        "utility_class": ".token-padding-end-300",
        "value": "12px",
        "usage": "Apply 12px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-300",
        "value": "12px",
        "usage": "Apply 12px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-300",
        "value": "12px",
        "usage": "Apply 12px padding to start"
    },
    {
        "utility_class": ".token-padding-400",
        "value": "16px",
        "usage": "Apply 16px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-400",
        "value": "16px",
        "usage": "Apply 16px padding to top"
    },
    {
        "utility_class": ".token-padding-end-400",
        "value": "16px",
        "usage": "Apply 16px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-400",
        "value": "16px",
        "usage": "Apply 16px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-400",
        "value": "16px",
        "usage": "Apply 16px padding to start"
    },
    {
        "utility_class": ".token-padding-500",
        "value": "20px",
        "usage": "Apply 20px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-500",
        "value": "20px",
        "usage": "Apply 20px padding to top"
    },
    {
        "utility_class": ".token-padding-end-500",
        "value": "20px",
        "usage": "Apply 20px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-500",
        "value": "20px",
        "usage": "Apply 20px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-500",
        "value": "20px",
        "usage": "Apply 20px padding to start"
    },
    {
        "utility_class": ".token-padding-600",
        "value": "24px",
        "usage": "Apply 24px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-600",
        "value": "24px",
        "usage": "Apply 24px padding to top"
    },
    {
        "utility_class": ".token-padding-end-600",
        "value": "24px",
        "usage": "Apply 24px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-600",
        "value": "24px",
        "usage": "Apply 24px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-600",
        "value": "24px",
        "usage": "Apply 24px padding to start"
    },
    {
        "utility_class": ".token-padding-700",
        "value": "28px",
        "usage": "Apply 28px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-700",
        "value": "28px",
        "usage": "Apply 28px padding to top"
    },
    {
        "utility_class": ".token-padding-end-700",
        "value": "28px",
        "usage": "Apply 28px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-700",
        "value": "28px",
        "usage": "Apply 28px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-700",
        "value": "28px",
        "usage": "Apply 28px padding to start"
    },
    {
        "utility_class": ".token-padding-800",
        "value": "32px",
        "usage": "Apply 32px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-800",
        "value": "32px",
        "usage": "Apply 32px padding to top"
    },
    {
        "utility_class": ".token-padding-end-800",
        "value": "32px",
        "usage": "Apply 32px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-800",
        "value": "32px",
        "usage": "Apply 32px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-800",
        "value": "32px",
        "usage": "Apply 32px padding to start"
    },
    {
        "utility_class": ".token-padding-900",
        "value": "36px",
        "usage": "Apply 36px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-900",
        "value": "36px",
        "usage": "Apply 36px padding to top"
    },
    {
        "utility_class": ".token-padding-end-900",
        "value": "36px",
        "usage": "Apply 36px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-900",
        "value": "36px",
        "usage": "Apply 36px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-900",
        "value": "36px",
        "usage": "Apply 36px padding to start"
    },
    {
        "utility_class": ".token-padding-1000",
        "value": "40px",
        "usage": "Apply 40px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1000",
        "value": "40px",
        "usage": "Apply 40px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1000",
        "value": "40px",
        "usage": "Apply 40px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1000",
        "value": "40px",
        "usage": "Apply 40px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1000",
        "value": "40px",
        "usage": "Apply 40px padding to start"
    },
    {
        "utility_class": ".token-padding-1100",
        "value": "44px",
        "usage": "Apply 44px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1100",
        "value": "44px",
        "usage": "Apply 44px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1100",
        "value": "44px",
        "usage": "Apply 44px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1100",
        "value": "44px",
        "usage": "Apply 44px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1100",
        "value": "44px",
        "usage": "Apply 44px padding to start"
    },
    {
        "utility_class": ".token-padding-1200",
        "value": "48px",
        "usage": "Apply 48px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1200",
        "value": "48px",
        "usage": "Apply 48px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1200",
        "value": "48px",
        "usage": "Apply 48px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1200",
        "value": "48px",
        "usage": "Apply 48px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1200",
        "value": "48px",
        "usage": "Apply 48px padding to start"
    },
    {
        "utility_class": ".token-padding-1400",
        "value": "56px",
        "usage": "Apply 56px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1400",
        "value": "56px",
        "usage": "Apply 56px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1400",
        "value": "56px",
        "usage": "Apply 56px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1400",
        "value": "56px",
        "usage": "Apply 56px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1400",
        "value": "56px",
        "usage": "Apply 56px padding to start"
    },
    {
        "utility_class": ".token-padding-1600",
        "value": "64px",
        "usage": "Apply 64px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1600",
        "value": "64px",
        "usage": "Apply 64px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1600",
        "value": "64px",
        "usage": "Apply 64px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1600",
        "value": "64px",
        "usage": "Apply 64px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1600",
        "value": "64px",
        "usage": "Apply 64px padding to start"
    },
    {
        "utility_class": ".token-padding-1800",
        "value": "72px",
        "usage": "Apply 72px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-1800",
        "value": "72px",
        "usage": "Apply 72px padding to top"
    },
    {
        "utility_class": ".token-padding-end-1800",
        "value": "72px",
        "usage": "Apply 72px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-1800",
        "value": "72px",
        "usage": "Apply 72px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-1800",
        "value": "72px",
        "usage": "Apply 72px padding to start"
    },
    {
        "utility_class": ".token-padding-2000",
        "value": "80px",
        "usage": "Apply 80px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-2000",
        "value": "80px",
        "usage": "Apply 80px padding to top"
    },
    {
        "utility_class": ".token-padding-end-2000",
        "value": "80px",
        "usage": "Apply 80px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-2000",
        "value": "80px",
        "usage": "Apply 80px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-2000",
        "value": "80px",
        "usage": "Apply 80px padding to start"
    },
    {
        "utility_class": ".token-padding-2400",
        "value": "96px",
        "usage": "Apply 96px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-2400",
        "value": "96px",
        "usage": "Apply 96px padding to top"
    },
    {
        "utility_class": ".token-padding-end-2400",
        "value": "96px",
        "usage": "Apply 96px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-2400",
        "value": "96px",
        "usage": "Apply 96px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-2400",
        "value": "96px",
        "usage": "Apply 96px padding to start"
    },
    {
        "utility_class": ".token-padding-2800",
        "value": "112px",
        "usage": "Apply 112px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-2800",
        "value": "112px",
        "usage": "Apply 112px padding to top"
    },
    {
        "utility_class": ".token-padding-end-2800",
        "value": "112px",
        "usage": "Apply 112px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-2800",
        "value": "112px",
        "usage": "Apply 112px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-2800",
        "value": "112px",
        "usage": "Apply 112px padding to start"
    },
    {
        "utility_class": ".token-padding-3200",
        "value": "128px",
        "usage": "Apply 128px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-3200",
        "value": "128px",
        "usage": "Apply 128px padding to top"
    },
    {
        "utility_class": ".token-padding-end-3200",
        "value": "128px",
        "usage": "Apply 128px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-3200",
        "value": "128px",
        "usage": "Apply 128px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-3200",
        "value": "128px",
        "usage": "Apply 128px padding to start"
    },
    {
        "utility_class": ".token-padding-3400",
        "value": "136px",
        "usage": "Apply 136px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-3400",
        "value": "136px",
        "usage": "Apply 136px padding to top"
    },
    {
        "utility_class": ".token-padding-end-3400",
        "value": "136px",
        "usage": "Apply 136px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-3400",
        "value": "136px",
        "usage": "Apply 136px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-3400",
        "value": "136px",
        "usage": "Apply 136px padding to start"
    },
    {
        "utility_class": ".token-padding-3600",
        "value": "144px",
        "usage": "Apply 144px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-3600",
        "value": "144px",
        "usage": "Apply 144px padding to top"
    },
    {
        "utility_class": ".token-padding-end-3600",
        "value": "144px",
        "usage": "Apply 144px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-3600",
        "value": "144px",
        "usage": "Apply 144px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-3600",
        "value": "144px",
        "usage": "Apply 144px padding to start"
    },
    {
        "utility_class": ".token-padding-4000",
        "value": "160px",
        "usage": "Apply 160px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-4000",
        "value": "160px",
        "usage": "Apply 160px padding to top"
    },
    {
        "utility_class": ".token-padding-end-4000",
        "value": "160px",
        "usage": "Apply 160px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-4000",
        "value": "160px",
        "usage": "Apply 160px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-4000",
        "value": "160px",
        "usage": "Apply 160px padding to start"
    },
    {
        "utility_class": ".token-padding-5000",
        "value": "200px",
        "usage": "Apply 200px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-5000",
        "value": "200px",
        "usage": "Apply 200px padding to top"
    },
    {
        "utility_class": ".token-padding-end-5000",
        "value": "200px",
        "usage": "Apply 200px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-5000",
        "value": "200px",
        "usage": "Apply 200px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-5000",
        "value": "200px",
        "usage": "Apply 200px padding to start"
    },
    {
        "utility_class": ".token-padding-6200",
        "value": "248px",
        "usage": "Apply 248px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-6200",
        "value": "248px",
        "usage": "Apply 248px padding to top"
    },
    {
        "utility_class": ".token-padding-end-6200",
        "value": "248px",
        "usage": "Apply 248px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-6200",
        "value": "248px",
        "usage": "Apply 248px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-6200",
        "value": "248px",
        "usage": "Apply 248px padding to start"
    },
    {
        "utility_class": ".token-padding-7400",
        "value": "296px",
        "usage": "Apply 296px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-7400",
        "value": "296px",
        "usage": "Apply 296px padding to top"
    },
    {
        "utility_class": ".token-padding-end-7400",
        "value": "296px",
        "usage": "Apply 296px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-7400",
        "value": "296px",
        "usage": "Apply 296px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-7400",
        "value": "296px",
        "usage": "Apply 296px padding to start"
    },
    {
        "utility_class": ".token-padding-9000",
        "value": "360px",
        "usage": "Apply 360px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top-9000",
        "value": "360px",
        "usage": "Apply 360px padding to top"
    },
    {
        "utility_class": ".token-padding-end-9000",
        "value": "360px",
        "usage": "Apply 360px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom-9000",
        "value": "360px",
        "usage": "Apply 360px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start-9000",
        "value": "360px",
        "usage": "Apply 360px padding to start"
    },
    {
        "utility_class": ".token-padding",
        "value": "16px",
        "usage": "Apply 16px padding to all sides"
    },
    {
        "utility_class": ".token-padding-top",
        "value": "16px",
        "usage": "Apply 16px padding to top"
    },
    {
        "utility_class": ".token-padding-end",
        "value": "16px",
        "usage": "Apply 16px padding to end"
    },
    {
        "utility_class": ".token-padding-bottom",
        "value": "16px",
        "usage": "Apply 16px padding to bottom"
    },
    {
        "utility_class": ".token-padding-start",
        "value": "16px",
        "usage": "Apply 16px padding to start"
    },
    {
        "utility_class": ".token-padding-vertical",
        "value": "16px",
        "usage": "Apply 16px padding to top and bottom"
    },
    {
        "utility_class": ".token-padding-horizontal",
        "value": "16px",
        "usage": "Apply 16px padding to start and end"
    },
    {
        "utility_class": ".token-no-padding",
        "value": "0px",
        "usage": "Apply 0px padding to all sides"
    }
];

export const Gap = [
    {
        "utility_class": ".token-gap-0",
        "value": "0px",
        "usage": "Sets gap spacing to 0px"
    },
    {
        "utility_class": ".token-gap-050",
        "value": "2px",
        "usage": "Sets gap spacing to 2px"
    },
    {
        "utility_class": ".token-gap-100",
        "value": "4px",
        "usage": "Sets gap spacing to 4px"
    },
    {
        "utility_class": ".token-gap-150",
        "value": "6px",
        "usage": "Sets gap spacing to 6px"
    },
    {
        "utility_class": ".token-gap-200",
        "value": "8px",
        "usage": "Sets gap spacing to 8px"
    },
    {
        "utility_class": ".token-gap-250",
        "value": "10px",
        "usage": "Sets gap spacing to 10px"
    },
    {
        "utility_class": ".token-gap-300",
        "value": "12px",
        "usage": "Sets gap spacing to 12px"
    },
    {
        "utility_class": ".token-gap-400",
        "value": "16px",
        "usage": "Sets gap spacing to 16px"
    },
    {
        "utility_class": ".token-gap-500",
        "value": "20px",
        "usage": "Sets gap spacing to 20px"
    },
    {
        "utility_class": ".token-gap-600",
        "value": "24px",
        "usage": "Sets gap spacing to 24px"
    },
    {
        "utility_class": ".token-gap-700",
        "value": "28px",
        "usage": "Sets gap spacing to 28px"
    },
    {
        "utility_class": ".token-gap-800",
        "value": "32px",
        "usage": "Sets gap spacing to 32px"
    },
    {
        "utility_class": ".token-gap-900",
        "value": "36px",
        "usage": "Sets gap spacing to 36px"
    },
    {
        "utility_class": ".token-gap-1000",
        "value": "40px",
        "usage": "Sets gap spacing to 40px"
    },
    {
        "utility_class": ".token-gap-1100",
        "value": "44px",
        "usage": "Sets gap spacing to 44px"
    },
    {
        "utility_class": ".token-gap-1200",
        "value": "48px",
        "usage": "Sets gap spacing to 48px"
    },
    {
        "utility_class": ".token-gap-1400",
        "value": "56px",
        "usage": "Sets gap spacing to 56px"
    },
    {
        "utility_class": ".token-gap-1600",
        "value": "64px",
        "usage": "Sets gap spacing to 64px"
    },
    {
        "utility_class": ".token-gap-1800",
        "value": "72px",
        "usage": "Sets gap spacing to 72px"
    },
    {
        "utility_class": ".token-gap-2000",
        "value": "80px",
        "usage": "Sets gap spacing to 80px"
    },
    {
        "utility_class": ".token-gap-2400",
        "value": "96px",
        "usage": "Sets gap spacing to 96px"
    },
    {
        "utility_class": ".token-gap-2800",
        "value": "112px",
        "usage": "Sets gap spacing to 112px"
    },
    {
        "utility_class": ".token-gap-3200",
        "value": "128px",
        "usage": "Sets gap spacing to 128px"
    },
    {
        "utility_class": ".token-gap-3400",
        "value": "136px",
        "usage": "Sets gap spacing to 136px"
    },
    {
        "utility_class": ".token-gap-3600",
        "value": "144px",
        "usage": "Sets gap spacing to 144px"
    },
    {
        "utility_class": ".token-gap-4000",
        "value": "160px",
        "usage": "Sets gap spacing to 160px"
    },
    {
        "utility_class": ".token-gap-5000",
        "value": "200px",
        "usage": "Sets gap spacing to 200px"
    },
    {
        "utility_class": ".token-gap-6200",
        "value": "248px",
        "usage": "Sets gap spacing to 248px"
    },
    {
        "utility_class": ".token-gap-7400",
        "value": "296px",
        "usage": "Sets gap spacing to 296px"
    },
    {
        "utility_class": ".token-gap-9000",
        "value": "360px",
        "usage": "Sets gap spacing to 360px"
    }
];
