// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Regenerate: npm run docs:tokens (requires npm run build:tokens first)
export const Transition = [
    {
        "token": "transition.time.0",
        "css_variable": "--token-transition-time-0",
        "utility_class": ".token-transition-time-0",
        "value": "0ms"
    },
    {
        "token": "transition.time.100",
        "css_variable": "--token-transition-time-100",
        "utility_class": ".token-transition-time-100",
        "value": "100ms"
    },
    {
        "token": "transition.time.1000",
        "css_variable": "--token-transition-time-1000",
        "utility_class": ".token-transition-time-1000",
        "value": "1000ms"
    },
    {
        "token": "transition.time.150",
        "css_variable": "--token-transition-time-150",
        "utility_class": ".token-transition-time-150",
        "value": "150ms"
    },
    {
        "token": "transition.time.1500",
        "css_variable": "--token-transition-time-1500",
        "utility_class": ".token-transition-time-1500",
        "value": "1500ms"
    },
    {
        "token": "transition.time.200",
        "css_variable": "--token-transition-time-200",
        "utility_class": ".token-transition-time-200",
        "value": "200ms"
    },
    {
        "token": "transition.time.300",
        "css_variable": "--token-transition-time-300",
        "utility_class": ".token-transition-time-300",
        "value": "300ms"
    },
    {
        "token": "transition.time.500",
        "css_variable": "--token-transition-time-500",
        "utility_class": ".token-transition-time-500",
        "value": "500ms"
    }
];

export const TransitionCurve = [
    {
        "token": "transition.curve.base",
        "css_variable": "--token-transition-curve-base",
        "utility_class": ".token-transition-curve-base",
        "value": "cubic-bezier(0.4, 0, 1, 1)"
    },
    {
        "token": "transition.curve.bounce",
        "css_variable": "--token-transition-curve-bounce",
        "utility_class": ".token-transition-curve-bounce",
        "value": "cubic-bezier(0.47, 0, 0.23, 1.38)"
    },
    {
        "token": "transition.curve.expressive",
        "css_variable": "--token-transition-curve-expressive",
        "utility_class": ".token-transition-curve-expressive",
        "value": "cubic-bezier(0.4, 0, 0.2, 1)"
    },
    {
        "token": "transition.curve.linear",
        "css_variable": "--token-transition-curve-linear",
        "utility_class": ".token-transition-curve-linear",
        "value": "linear"
    },
    {
        "token": "transition.curve.quick",
        "css_variable": "--token-transition-curve-quick",
        "utility_class": ".token-transition-curve-quick",
        "value": "cubic-bezier(0, 0, 0.2, 1)"
    },
    {
        "token": "transition.curve.smooth",
        "css_variable": "--token-transition-curve-smooth",
        "utility_class": ".token-transition-curve-smooth",
        "value": "cubic-bezier(0.25, 1, 0.5, 1)"
    },
    {
        "token": "transition.curve.spring",
        "css_variable": "--token-transition-curve-spring",
        "utility_class": ".token-transition-curve-spring",
        "value": "cubic-bezier(0.16, 1, 0.3, 1)"
    }
];
