// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Regenerate: npm run docs:tokens (requires npm run build:tokens first)
export const Display = [
    {
        "token": "display.sm.light",
        "name": "Display sm light",
        "typeface": "Inter",
        "size": {
            "token": "scale.800",
            "value": "2rem"
        },
        "line_height": {
            "token": "scale.1100",
            "value": "2.75rem"
        },
        "weight": {
            "token": "font-weight.light",
            "value": "300"
        }
    },
    {
        "token": "display.sm.regular",
        "name": "Display sm regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.800",
            "value": "2rem"
        },
        "line_height": {
            "token": "scale.1100",
            "value": "2.75rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "display.lg.light",
        "name": "Display lg light",
        "typeface": "Inter",
        "size": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "line_height": {
            "token": "scale.1200",
            "value": "3rem"
        },
        "weight": {
            "token": "font-weight.light",
            "value": "300"
        }
    },
    {
        "token": "display.lg.regular",
        "name": "Display lg regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "line_height": {
            "token": "scale.1200",
            "value": "3rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    }
];

export const Heading = [
    {
        "token": "heading.h1.medium",
        "name": "Heading 1 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h1.regular",
        "name": "Heading 1 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h1.semi.bold",
        "name": "Heading 1 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h1.bold",
        "name": "Heading 1 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "heading.h2.medium",
        "name": "Heading 2 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.650",
            "value": "1.625rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h2.regular",
        "name": "Heading 2 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.650",
            "value": "1.625rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h2.semi.bold",
        "name": "Heading 2 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.650",
            "value": "1.625rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h2.bold",
        "name": "Heading 2 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.650",
            "value": "1.625rem"
        },
        "line_height": {
            "token": "scale.900",
            "value": "2.25rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "heading.h3.medium",
        "name": "Heading 3 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "line_height": {
            "token": "scale.800",
            "value": "2rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h3.regular",
        "name": "Heading 3 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "line_height": {
            "token": "scale.800",
            "value": "2rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h3.semi.bold",
        "name": "Heading 3 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "line_height": {
            "token": "scale.800",
            "value": "2rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h3.bold",
        "name": "Heading 3 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "line_height": {
            "token": "scale.800",
            "value": "2rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "heading.h4.medium",
        "name": "Heading 4 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.550",
            "value": "1.375rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h4.regular",
        "name": "Heading 4 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.550",
            "value": "1.375rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h4.semi.bold",
        "name": "Heading 4 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.550",
            "value": "1.375rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h4.bold",
        "name": "Heading 4 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.550",
            "value": "1.375rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "heading.h5.medium",
        "name": "Heading 5 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h5.regular",
        "name": "Heading 5 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h5.semi.bold",
        "name": "Heading 5 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h5.bold",
        "name": "Heading 5 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "heading.h6.medium",
        "name": "Heading 6 medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.450",
            "value": "1.125rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "heading.h6.regular",
        "name": "Heading 6 regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.450",
            "value": "1.125rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "heading.h6.semi.bold",
        "name": "Heading 6 semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.450",
            "value": "1.125rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "heading.h6.bold",
        "name": "Heading 6 bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.450",
            "value": "1.125rem"
        },
        "line_height": {
            "token": "scale.700",
            "value": "1.75rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    }
];

export const Body = [
    {
        "token": "body.lg.medium",
        "name": "Body lg medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.400",
            "value": "1rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.lg.regular",
        "name": "Body lg regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.400",
            "value": "1rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "body.lg.semi.bold",
        "name": "Body lg semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.400",
            "value": "1rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "body.lg.bold",
        "name": "Body lg bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.400",
            "value": "1rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "body.md.medium",
        "name": "Body md medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.350",
            "value": "0.875rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.md.regular",
        "name": "Body md regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.350",
            "value": "0.875rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "body.md.semi.bold",
        "name": "Body md semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.350",
            "value": "0.875rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "body.md.bold",
        "name": "Body md bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.350",
            "value": "0.875rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "body.sm.medium",
        "name": "Body sm medium",
        "typeface": "Inter",
        "size": {
            "token": "scale.300",
            "value": "0.75rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.sm.regular",
        "name": "Body sm regular",
        "typeface": "Inter",
        "size": {
            "token": "scale.300",
            "value": "0.75rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.regular",
            "value": "400"
        }
    },
    {
        "token": "body.sm.semi.bold",
        "name": "Body sm semi",
        "typeface": "Inter",
        "size": {
            "token": "scale.300",
            "value": "0.75rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.semi-bold",
            "value": "600"
        }
    },
    {
        "token": "body.sm.bold",
        "name": "Body sm bold",
        "typeface": "Inter",
        "size": {
            "token": "scale.300",
            "value": "0.75rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.bold",
            "value": "700"
        }
    },
    {
        "token": "body.action.lg",
        "name": "Body action lg",
        "typeface": "Inter",
        "size": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.action.md",
        "name": "Body action md",
        "typeface": "Inter",
        "size": {
            "token": "scale.400",
            "value": "1rem"
        },
        "line_height": {
            "token": "scale.600",
            "value": "1.5rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.action.sm",
        "name": "Body action sm",
        "typeface": "Inter",
        "size": {
            "token": "scale.350",
            "value": "0.875rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    },
    {
        "token": "body.action.xs",
        "name": "Body action xs",
        "typeface": "Inter",
        "size": {
            "token": "scale.300",
            "value": "0.75rem"
        },
        "line_height": {
            "token": "scale.500",
            "value": "1.25rem"
        },
        "weight": {
            "token": "font-weight.medium",
            "value": "500"
        }
    }
];

export const FontFamily = [
    {
        "token": "font.family",
        "css_variable": "--token-font-family",
        "utility_class": ".token-font-family",
        "value": "Inter, sans-serif"
    }
];

export const Weight = [
    {
        "token": "font.weight.thin",
        "css_variable": "--token-font-weight-thin",
        "utility_class": ".token-font-weight-thin",
        "value": "100"
    },
    {
        "token": "font.weight.extra-light",
        "css_variable": "--token-font-weight-extra-light",
        "utility_class": ".token-font-weight-extra-light",
        "value": "200"
    },
    {
        "token": "font.weight.light",
        "css_variable": "--token-font-weight-light",
        "utility_class": ".token-font-weight-light",
        "value": "300"
    },
    {
        "token": "font.weight.regular",
        "css_variable": "--token-font-weight-regular",
        "utility_class": ".token-font-weight-regular",
        "value": "400"
    },
    {
        "token": "font.weight.medium",
        "css_variable": "--token-font-weight-medium",
        "utility_class": ".token-font-weight-medium",
        "value": "500"
    },
    {
        "token": "font.weight.semi-bold",
        "css_variable": "--token-font-weight-semi-bold",
        "utility_class": ".token-font-weight-semi-bold",
        "value": "600"
    },
    {
        "token": "font.weight.bold",
        "css_variable": "--token-font-weight-bold",
        "utility_class": ".token-font-weight-bold",
        "value": "700"
    },
    {
        "token": "font.weight.extra-bold",
        "css_variable": "--token-font-weight-extra-bold",
        "utility_class": ".token-font-weight-extra-bold",
        "value": "800"
    },
    {
        "token": "font.weight.black",
        "css_variable": "--token-font-weight-black",
        "utility_class": ".token-font-weight-black",
        "value": "900"
    }
];

export const Size = [
    {
        "token": "font.size.250",
        "css_variable": "--token-font-size-250",
        "utility_class": ".token-font-size-250",
        "value": "0.625rem"
    },
    {
        "token": "font.size.275",
        "css_variable": "--token-font-size-275",
        "utility_class": ".token-font-size-275",
        "value": "0.6875rem"
    },
    {
        "token": "font.size.300",
        "css_variable": "--token-font-size-300",
        "utility_class": ".token-font-size-300",
        "value": "0.75rem"
    },
    {
        "token": "font.size.350",
        "css_variable": "--token-font-size-350",
        "utility_class": ".token-font-size-350",
        "value": "0.875rem"
    },
    {
        "token": "font.size.400",
        "css_variable": "--token-font-size-400",
        "utility_class": ".token-font-size-400",
        "value": "1rem"
    },
    {
        "token": "font.size.450",
        "css_variable": "--token-font-size-450",
        "utility_class": ".token-font-size-450",
        "value": "1.125rem"
    },
    {
        "token": "font.size.500",
        "css_variable": "--token-font-size-500",
        "utility_class": ".token-font-size-500",
        "value": "1.25rem"
    },
    {
        "token": "font.size.550",
        "css_variable": "--token-font-size-550",
        "utility_class": ".token-font-size-550",
        "value": "1.375rem"
    },
    {
        "token": "font.size.600",
        "css_variable": "--token-font-size-600",
        "utility_class": ".token-font-size-600",
        "value": "1.5rem"
    },
    {
        "token": "font.size.650",
        "css_variable": "--token-font-size-650",
        "utility_class": ".token-font-size-650",
        "value": "1.625rem"
    },
    {
        "token": "font.size.700",
        "css_variable": "--token-font-size-700",
        "utility_class": ".token-font-size-700",
        "value": "1.75rem"
    },
    {
        "token": "font.size.800",
        "css_variable": "--token-font-size-800",
        "utility_class": ".token-font-size-800",
        "value": "2rem"
    },
    {
        "token": "font.size.900",
        "css_variable": "--token-font-size-900",
        "utility_class": ".token-font-size-900",
        "value": "2.25rem"
    }
];

export const LetterSpacing = [
    {
        "token": "font.letter.spacing.0",
        "css_variable": "--token-font-letter-spacing-0",
        "utility_class": ".token-font-letter-spacing-0",
        "value": "0"
    },
    {
        "token": "font.letter.spacing.100",
        "css_variable": "--token-font-letter-spacing-100",
        "utility_class": ".token-font-letter-spacing-100",
        "value": "0.01em"
    },
    {
        "token": "font.letter.spacing.150",
        "css_variable": "--token-font-letter-spacing-150",
        "utility_class": ".token-font-letter-spacing-150",
        "value": "0.015em"
    }
];

export const LineHeight = [
    {
        "token": "font.line.height.300",
        "css_variable": "--token-font-line-height-300",
        "utility_class": ".token-font-line-height-300",
        "value": "0.75rem"
    },
    {
        "token": "font.line.height.400",
        "css_variable": "--token-font-line-height-400",
        "utility_class": ".token-font-line-height-400",
        "value": "1rem"
    },
    {
        "token": "font.line.height.500",
        "css_variable": "--token-font-line-height-500",
        "utility_class": ".token-font-line-height-500",
        "value": "1.25rem"
    },
    {
        "token": "font.line.height.600",
        "css_variable": "--token-font-line-height-600",
        "utility_class": ".token-font-line-height-600",
        "value": "1.5rem"
    },
    {
        "token": "font.line.height.700",
        "css_variable": "--token-font-line-height-700",
        "utility_class": ".token-font-line-height-700",
        "value": "1.75rem"
    },
    {
        "token": "font.line.height.800",
        "css_variable": "--token-font-line-height-800",
        "utility_class": ".token-font-line-height-800",
        "value": "2rem"
    },
    {
        "token": "font.line.height.900",
        "css_variable": "--token-font-line-height-900",
        "utility_class": ".token-font-line-height-900",
        "value": "2.25rem"
    },
    {
        "token": "font.line.height.1100",
        "css_variable": "--token-font-line-height-1100",
        "utility_class": ".token-font-line-height-1100",
        "value": "2.75rem"
    },
    {
        "token": "font.line.height.1200",
        "css_variable": "--token-font-line-height-1200",
        "utility_class": ".token-font-line-height-1200",
        "value": "3rem"
    }
];
