trigger: none

pr:
    branches:
        include:
            - '*' # This does not trigger the pipeline

jobs:
    - job: CheckChanges
      displayName: 'Check changed files'
      steps:
          - bash: |
                CHANGED_FILES=$(git diff origin/dev --name-only)
                echo "Checking for file changes..."
                declare TAGS

                for FILE in $CHANGED_FILES
                    do
                        if [[ $FILE == *"src/scripts/OSUIFramework/Pattern"* ]] || [[ $FILE == *"src/scss/04-patterns"* ]]; then
                            ELEMENT=$(echo $FILE| cut -d/ -f5)
                            if [[ -z "$TAGS" ]]; then
                                TAGS="@$ELEMENT"
                            else
                                TAGS="$TAGS or @$ELEMENT"
                            fi
                            continue
                        fi

                        if [[ $FILE == *"src/static"* ]]; then
                            ELEMENT=$(echo $FILE| cut -d/ -f3)
                            if [[ -z "$TAGS" ]]; then
                                TAGS="@$ELEMENT"
                            else
                                TAGS="$TAGS or @$ELEMENT"
                            fi
                            continue
                        fi
                        echo "IGNORE: ${FILE} changed"
                    done
                echo "##vso[task.setvariable variable=tags;isoutput=true]$TAGS"
            name: check_changes
            displayName: 'Check changed files'
          - script: echo $(check_changes.tags)
            name: echoTags
            displayName: 'Show components to run tests for'

    - job: ExecuteFunctionalTests
      dependsOn: CheckChanges
      displayName: 'Execute Functional Tests'
      variables:
          TAGS: $[ dependencies.CheckChanges.outputs['check_changes.tags'] ]
      steps:
          - task: NodeTool@0
            displayName: 'Use Node 14.15.4'
            inputs:
                versionSpec: '14.15.4'
                checkLatest: true

          - bash: |
                echo "##vso[task.setvariable variable=branch;isoutput=true]$SYSTEM_PULLREQUEST_SOURCEBRANCH"
            name: branch_name

          - task: CmdLine@2
            name: install_dep
            displayName: 'Install dependencies using yarn'
            inputs:
                script: 'npm install'
            continueOnError: true
          - task: CmdLine@2
            displayName: Execute Pipeline
            inputs:
                script: node pipelines/pipeline-run.js -- --tags="$(TAGS)" --branch="$(branch_name.branch)"
