/*
 * GENERATED FILE — do not edit by hand.
 * Source: the pattern configuration classes and event enums, via scripts/generate-pattern-types.mjs (npm run types:generate).
 * Each block merges into the pattern's public API namespace and is emitted into the published .d.ts.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.AccordionAPI {
	/**
	 * Configuration accepted by AccordionAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Accordion configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Allows several items to be expanded at once; when false, expanding an item collapses the others. */
		MultipleItems?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.AccordionItemAPI {
	/**
	 * Configuration accepted by AccordionItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the AccordionItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Indicator icon: Caret, PlusMinus or Custom (a developer-supplied icon in the item's icon placeholder). */
		Icon?: 'Caret' | 'Custom' | 'PlusMinus';
		/** Side of the title where the indicator icon is rendered (left or right). (default from GlobalEnum.Direction; not validated — any string is accepted) */
		IconPosition?: string;
		/** Prevents the user from expanding or collapsing the item. */
		IsDisabled?: boolean;
		/** Renders the item already expanded when it is built. */
		StartsExpanded?: boolean;
		/** When true only the icon toggles the item; otherwise the whole title area does. */
		ToggleWithIcon?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.AnimatedLabelAPI {
	/**
	 * Configuration accepted by AnimatedLabelAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the AnimatedLabel configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.BottomSheetAPI {
	/**
	 * Configuration accepted by BottomSheetAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the BottomSheet configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Corner shape of the sheet: SoftRounded (default), Rounded or Sharp. */
		Shape?: 'soft' | 'none' | 'rounded';
		/** Shows the drag handler bar at the top of the sheet. */
		ShowHandler?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.ButtonLoadingAPI {
	/**
	 * Configuration accepted by ButtonLoadingAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the ButtonLoading configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Shows the loading spinner and blocks interaction while true. */
		IsLoading?: boolean;
		/** Keeps the button label visible next to the spinner; otherwise only the spinner shows while loading. */
		ShowLoadingAndLabel?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.CarouselAPI {
	/**
	 * Configuration accepted by CarouselAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Carousel configuration classes — do not edit.
	 */
	export type Configs = {
		/** Advances the slides automatically. */
		AutoPlay?: boolean;
		/** Slide direction: ltr, rtl or ttb (vertical). */
		Direction?: 'ltr' | 'rtl' | 'ttb';
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Height of the carousel (CSS length or pixel number); auto by default, required for the vertical direction. */
		Height?: string | number;
		/** Number of items visible at once on desktop. */
		ItemsDesktop?: number;
		/** Gap between items (CSS length or pixel number); 0px by default. */
		ItemsGap?: string | number;
		/** Number of items visible at once on phones. */
		ItemsPhone?: number;
		/** Number of items visible at once on tablets. */
		ItemsTablet?: number;
		/** Rewinds to the first item after the last one. */
		Loop?: boolean;
		/** Navigation controls to render: Arrows, Dots, Both or None. */
		Navigation?: 'both' | 'arrows' | 'dots' | 'none';
		/** Padding on both ends of the track so neighbouring items peek in (CSS length or pixel number). */
		Padding?: string | number;
		/** Zero-based index of the item shown first. */
		StartingPosition?: number;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | 'OnProviderConfigsApplied' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.DatePickerAPI {
	/**
	 * Configuration accepted by DatePickerAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the DatePicker configuration classes — do not edit.
	 */
	export type Configs = {
		/** Stores the ability to allow inputs to be editable or not */
		AllowInput?: boolean;
		/** Store calendar mode is in use */
		CalendarMode?: 'range' | 'single';
		/** Display format of the selected date (e.g. DD/MM/YYYY); empty uses the server date format. */
		DateFormat?: string;
		/** Stores the ability to disable a range of dates from datepicker Source type: Array<string | Date | ((date: Date) => boolean)> */
		Disable?: unknown[];
		/** Stores the ability to disable the mobile flatpickr behavior. False is the default provider option */
		DisableMobile?: boolean;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** First day of the week in the calendar (0 = Sunday … 6 = Saturday). */
		FirstWeekDay?: number;
		/** Set the property initialDate */
		InitialDate?: string | Date;
		/** Set the property EndDate */
		InitialEndDate?: string;
		/** Set the property StartDate */
		InitialStartDate?: string;
		/** Latest selectable date; empty for no upper limit. */
		MaxDate?: string;
		/** Earliest selectable date; empty for no lower limit. */
		MinDate?: string;
		/** Renders a Today button in the calendar footer. */
		ShowTodayButton?: boolean;
		/** Shows the week-number column in the calendar. */
		ShowWeekNumbers?: boolean;
		/** Time selection appended to the calendar: disabled (date only), 12 or 24 (hour format). */
		TimeFormat?: 'disabled' | '12' | '24';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | 'OnProviderConfigsApplied' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.DropdownAPI {
	/**
	 * Configuration accepted by DropdownAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Dropdown configuration classes — do not edit.
	 */
	export type Configs = {
		/** Properties */
		AllowMultipleSelection?: boolean;
		/** CSS id selector of the element the provider renders into; set by the pattern from its own element. */
		ElementId?: string;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Renders the dropdown disabled. */
		IsDisabled?: boolean;
		/** Message shown when there are no options. */
		NoOptionsText?: string;
		/** Message shown when a search matches no option. */
		NoResultsText?: string;
		/** Options to render: { value, label, image_url_or_class?, description?, group_name? }. Source type: DropDownOption[] */
		OptionsList?: unknown[];
		/** Viewport width (CSS length) below which the dropbox opens as a popup; set to the screen size on mobile. */
		PopupDropboxBreakpoint?: string;
		/** Placeholder shown while nothing is selected. */
		Prompt?: string;
		/** Escapes HTML in option labels and values before they are rendered. */
		SanitizeDropdownValues?: boolean;
		/** Placeholder of the search input. */
		SearchPrompt?: string;
		/** Opens the options list as a centred popup instead of an anchored dropbox (below PopupDropboxBreakpoint). */
		ShowDropboxAsPopup?: boolean;
		/** Options selected when the dropdown is built (same shape as OptionsList). Source type: DropDownOption[] */
		StartingSelection?: unknown[];
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName =
		| 'OnToggle'
		| 'beforeClose'
		| 'beforeOpen'
		| 'change'
		| 'OnSelected'
		| 'Initialized'
		| 'OnProviderConfigsApplied'
		| (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.DropdownServerSideItemAPI {
	/**
	 * Configuration accepted by DropdownServerSideItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the DropdownServerSideItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Marks the item as selected when it is built. */
		IsSelected?: boolean;
		/** Identifier of the item reported to the parent dropdown when it is selected. */
		ItemId?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnSelected' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.FlipContentAPI {
	/**
	 * Configuration accepted by FlipContentAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the FlipContent configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Flips the content when it is clicked; otherwise flipping happens only through the API. */
		FlipSelf?: boolean;
		/** Starts with the back face visible. */
		IsFlipped?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.GalleryAPI {
	/**
	 * Configuration accepted by GalleryAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Gallery configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Gap between items as a framework space name (none, xs, s, base, m, l, xl, xxl), mapped to --space-*. */
		ItemsGap?: string;
		/** Number of items per row on desktop. */
		RowItemsDesktop?: number;
		/** Number of items per row on phones. */
		RowItemsPhone?: number;
		/** Number of items per row on tablets. */
		RowItemsTablet?: number;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.InlineSvgAPI {
	/**
	 * Configuration accepted by InlineSvgAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the InlineSvg configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Raw <svg> markup rendered inline; invalid markup is rejected with a console error. */
		SVGCode?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.MonthPickerAPI {
	/**
	 * Configuration accepted by MonthPickerAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the MonthPicker configuration classes — do not edit.
	 */
	export type Configs = {
		/** Stores the ability to allow inputs to be editable or not */
		AllowInput?: boolean;
		/** Display format of the selected month (e.g. MM/YYYY). */
		DateFormat?: string;
		/** Stores the ability to disable the mobile flatpickr behavior. False is the default provider option */
		DisableMobile?: boolean;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Month selected when the picker is built ({ Month, Year }). */
		InitialMonth?: MonthYear;
		/** Latest selectable month ({ Month, Year }). */
		MaxMonth?: MonthYear;
		/** Earliest selectable month ({ Month, Year }). */
		MinMonth?: MonthYear;
		/** Store the Server Date format that will be used to casting the selected dates into a knowned date by/for Flatpickr */
		ServerDateFormat?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnSelected' | 'Initialized' | 'OnProviderConfigsApplied' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.NotificationAPI {
	/**
	 * Configuration accepted by NotificationAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Notification configuration classes — do not edit.
	 */
	export type Configs = {
		/** Milliseconds after which the notification closes itself; 0 or undefined keeps it open. */
		CloseAfterTime?: number;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Closes the notification on interaction outside it (click outside or Escape); ignored on native apps. */
		InteractToClose?: boolean;
		/** Enables swipe gestures to dismiss the notification. */
		NeedsSwipes?: boolean;
		/** Screen position: top (default), top-left, top-right, bottom, bottom-left, bottom-right or center. */
		Position?: 'top' | '370px';
		/** Shows the notification as soon as it is built. */
		StartsOpen?: boolean;
		/** Width of the notification (CSS length); 370px by default. */
		Width?: 'top' | '370px';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.OverflowMenuAPI {
	/**
	 * Configuration accepted by OverflowMenuAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the OverflowMenu configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Preferred placement of the menu relative to its trigger (GlobalEnum.FloatingPosition); auto picks the best fit. */
		Position?:
			| 'auto'
			| 'bottom'
			| 'bottom-end'
			| 'bottom-start'
			| 'center'
			| 'left'
			| 'left-end'
			| 'left-start'
			| 'right'
			| 'right-end'
			| 'right-start'
			| 'top'
			| 'top-end'
			| 'top-start';
		/** Corner shape of the menu: SoftRounded (default), Rounded or Sharp. */
		Shape?: 'soft' | 'none' | 'rounded';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.ProgressAPI {
	/**
	 * Configuration accepted by ProgressAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Progress configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.RangeSliderAPI {
	/**
	 * Configuration accepted by RangeSliderAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the RangeSlider configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** These variables hold the inital state of a RangeSlider */
		InitialValueFrom?: number;
		/** Value of the upper handle when the slider is built (interval mode). */
		InitialValueTo?: number;
		/** Renders the slider disabled. */
		IsDisabled?: boolean;
		/** Uses two handles (from/to) instead of a single one. */
		IsInterval?: boolean;
		/** Upper bound of the range. */
		MaxValue?: number;
		/** Lower bound of the range. */
		MinValue?: number;
		/** horizontal (default) or vertical. */
		Orientation?: 'horizontal' | 'vertical';
		/** Shows the current value in a floating label above the handle. */
		ShowFloatingLabel?: boolean;
		/** Renders tick marks (pips) along the track. */
		ShowTickMarks?: boolean;
		/** Track length (CSS length); 100% when horizontal, 100px when vertical. */
		Size?: string;
		/** Current value of the (lower) handle, kept across provider redraws. */
		StartingValueFrom?: number;
		/** Current value of the upper handle, kept across provider redraws (interval mode). */
		StartingValueTo?: number;
		/** Increment between selectable values. */
		Step?: number;
		/** Distance between tick marks in slider units. */
		TickMarksInterval?: number;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | 'OnProviderConfigsApplied' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.RatingAPI {
	/**
	 * Configuration accepted by RatingAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Rating configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Lets the user change the rating; when false it is read-only. */
		IsEdit?: boolean;
		/** Number of rating items (0–100). */
		RatingScale?: number;
		/** Current rating; decimals render a half-filled item. */
		RatingValue?: number;
		/** Size modifier appended as the rating-<Size> class (empty for the default size). */
		Size?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnSelected' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SearchAPI {
	/**
	 * Configuration accepted by SearchAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Search configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SectionIndexAPI {
	/**
	 * Configuration accepted by SectionIndexAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the SectionIndex configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Keeps the index fixed while the page scrolls. */
		IsFixed?: boolean;
		/** Animates the scroll to the target section. */
		SmoothScrolling?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SectionIndexItemAPI {
	/**
	 * Configuration accepted by SectionIndexItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the SectionIndexItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Id of the widget the page scrolls to when the item is clicked. */
		ScrollToWidgetId?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SidebarAPI {
	/**
	 * Configuration accepted by SidebarAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Sidebar configuration classes — do not edit.
	 */
	export type Configs = {
		/** PUBLIC PROPERTIES * */
		Direction?: 'right' | 'left';
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Dims the page behind the sidebar with an overlay while it is open (and closes on click outside). */
		HasOverlay?: boolean;
		/** Renders the sidebar open when it is built. */
		StartsOpen?: boolean;
		/** Width of the sidebar (CSS length); 500px by default. */
		Width?: '500px';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SubmenuAPI {
	/**
	 * Configuration accepted by SubmenuAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Submenu configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** PUBLIC PROPERTIES * */
		OpenOnHover?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.SwipeEventsAPI {
	/**
	 * Configuration accepted by SwipeEventsAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the SwipeEvents configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Id of the element that receives the swipe gesture listeners. */
		WidgetId?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'SwipeUp' | 'SwipeDown' | 'SwipeRight' | 'SwipeLeft' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TabsAPI {
	/**
	 * Configuration accepted by TabsAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Tabs configuration classes — do not edit.
	 */
	export type Configs = {
		/** Sizes the content area to the active tab instead of the tallest tab. */
		ContentAutoHeight?: boolean;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Height of the tabs content (CSS length); auto by default. (default from GlobalEnum.CssProperties; not validated — any string is accepted) */
		Height?: string;
		/** Stretches the header items to fill the available width. */
		JustifyHeaders?: boolean;
		/** Zero-based index of the tab active when built; cannot be changed afterwards. */
		StartingTab?: number;
		/** horizontal (headers above the content) or vertical (headers beside it). */
		TabsOrientation?: 'horizontal' | 'vertical';
		/** Side of the content where vertical headers sit: left or right. */
		TabsVerticalPosition?: 'left' | 'right';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnChange' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TabsContentItemAPI {
	/**
	 * Configuration accepted by TabsContentItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the TabsContentItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TabsHeaderItemAPI {
	/**
	 * Configuration accepted by TabsHeaderItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the TabsHeaderItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TimePickerAPI {
	/**
	 * Configuration accepted by TimePickerAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the TimePicker configuration classes — do not edit.
	 */
	export type Configs = {
		/** Stores the ability to allow inputs to be editable or not */
		AllowInput?: boolean;
		/** Stores the ability to disable the mobile flatpickr behavior. False is the default provider option */
		DisableMobile?: boolean;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** First day of the week (0 = Sunday); forwarded to the provider locale. */
		FirstWeekDay?: number;
		/** Time selected when the picker is built (HH:mm). */
		InitialTime?: string;
		/** Uses a 24-hour clock; false shows an AM/PM selector. */
		Is24Hours?: boolean;
		/** Latest selectable time (HH:mm). */
		MaxTime?: string;
		/** Earliest selectable time (HH:mm). */
		MinTime?: string;
		/** Store the Server Date format that will be used to casting the selected dates into a knowned date by/for Flatpickr */
		ServerDateFormat?: string;
		/** Display format of the selected time. */
		TimeFormat?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | 'OnProviderConfigsApplied' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TooltipAPI {
	/**
	 * Configuration accepted by TooltipAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Tooltip configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Opens on hover/focus; when false it opens on click. */
		IsHover?: boolean;
		/** Placement of the balloon relative to the trigger (GlobalEnum.Position). */
		Position?:
			'bottom' | 'bottom-left' | 'bottom-right' | 'center' | 'left' | 'right' | 'top' | 'top-left' | 'top-right';
		/** Shows the tooltip as soon as it is built. */
		StartVisible?: boolean;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnToggle' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.TouchEventsAPI {
	/**
	 * Configuration accepted by TouchEventsAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the TouchEvents configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Id of the element that receives the touch listeners. */
		WidgetId?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'End' | 'Move' | 'Start' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.VideoAPI {
	/**
	 * Configuration accepted by VideoAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Video configuration classes — do not edit.
	 */
	export type Configs = {
		/** Starts playback automatically (browsers may require Muted). */
		Autoplay?: boolean;
		/** JSON list of caption tracks: [{ LanguageCode, SourceFile, Label }]. */
		Captions?: string;
		/** Shows the native player controls. */
		Controls?: boolean;
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Height of the player (CSS length). */
		Height?: string;
		/** Restarts playback when the video ends. */
		Loop?: boolean;
		/** Starts muted. */
		Muted?: boolean;
		/** Image shown before playback starts. */
		PosterURL?: string;
		/** Video source: a URL or a base64 data URL. */
		URL?: string;
		/** Width of the player (CSS length). */
		Width?: string;
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'StateChanged' | 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.WizardAPI {
	/**
	 * Configuration accepted by WizardAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the Wizard configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** Stacks the steps vertically. */
		IsVertical?: boolean;
		/** Interactive lets users navigate by clicking steps; ProgressOnly makes steps read-only indicators. */
		StepBehavior?: 'Interactive' | 'ProgressOnly';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'Initialized' | (string & {});
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OutSystems.OSUI.Patterns.WizardItemAPI {
	/**
	 * Configuration accepted by WizardItemAPI.Create, as an object or as its JSON string.
	 * Generated by scripts/generate-pattern-types.mjs from the WizardItem configuration classes — do not edit.
	 */
	export type Configs = {
		/** Extra CSS classes applied to the pattern root element. */
		ExtendedClass?: string;
		/** ReverseLabelPosition property value */
		ReverseLabelPosition?: boolean;
		/** Status property value */
		Status?: 'active' | 'next' | 'past';
	};

	/** Event names understood by RegisterCallback; any other string is passed through unchanged. */
	export type EventName = 'OnClick' | 'Initialized' | (string & {});
}
