// @ts-check
/**
 * Generates `src/scripts/OutSystems/OSUI/Patterns/PatternTypes.ts`: for every pattern a namespace
 * block merged into its public API namespace with
 *
 *   export type Configs   — the configuration object `Create` accepts (also as a JSON string)
 *   export type EventName — the event names `RegisterCallback` understands (+ a string escape hatch)
 *
 * The types are derived from the same source readers as docs-ai/, so they cannot drift from the
 * configuration classes. They stay inside the public layer: no `Providers.*`/`OSFramework.*`
 * references (T2); provider-typed values degrade to `unknown` with the source type noted.
 */
import path from 'node:path';

import prettier from 'prettier';

import { expectationsFor } from '../../evals/lib/expectations.mjs';
import { resolveEnumReference } from './ai-docs.mjs';

export const OUTPUT_FILE = 'src/scripts/OutSystems/OSUI/Patterns/PatternTypes.ts';
const GENERATOR = 'scripts/generate-pattern-types.mjs';

const PRIMITIVE = /^(string|number|boolean|Date|MonthYear|'[^']*'|-?\d+(\.\d+)?|true|false)$/;
const INTERNAL_CALLBACK = /Callbacks|Generic/;

/**
 * TypeScript type text usable inside `OutSystems.OSUI.Patterns.*` for a manifest prop type.
 * @param {import('../../evals/lib/context.mjs').EvalContext} ctx
 * @param {import('../../evals/lib/inventory.mjs').Pattern} pattern
 * @param {string} type manifest type text
 * @param {import('../../evals/lib/ts.mjs').ConfigProp} prop
 * @returns {{ type: string, note?: string }}
 */
function publicType(ctx, pattern, type, prop) {
	const parts = type.split(' | ').map((p) => p.trim());
	if (parts.every((p) => PRIMITIVE.test(p))) return { type };
	// enum member references (GlobalEnum.Direction.LTR | …) → literal values
	const resolved = parts.map((p) => resolveEnumReference(ctx, pattern, p));
	if (resolved.every((v) => v !== null)) {
		return { type: resolved.map((v) => (typeof v === 'string' ? `'${v}'` : String(v))).join(' | ') };
	}
	if (prop.kind === 'array' || type === 'array' || type.endsWith('[]'))
		return { type: 'unknown[]', note: `Source type: ${prop.typeText ?? type}` };
	return { type: 'unknown', note: `Source type: ${prop.typeText ?? type}` };
}

/** @param {string} text */
const jsdocLine = (text) => `/** ${text.replace(/\*\//g, '* /').trim()} */`;

/** Code-point order, which is what the member-ordering lint rule ("alphabetically") checks. */
const codePointCompare = (/** @type {string} */ a, /** @type {string} */ b) => (a < b ? -1 : Number(a > b));

/**
 * Generated source, formatted with the repository Prettier configuration so it is stable and lint-clean.
 * @param {import('../../evals/lib/context.mjs').EvalContext} ctx
 * @param {ReturnType<typeof import('./ai-docs.mjs').buildManifest>} manifest
 * @returns {Promise<string>}
 */
export async function renderPatternTypes(ctx, manifest) {
	const raw = renderPatternTypesRaw(ctx, manifest);
	const config = (await prettier.resolveConfig(path.join(ctx.root, OUTPUT_FILE))) ?? {};
	return prettier.format(raw, { ...config, filepath: path.join(ctx.root, OUTPUT_FILE) });
}

/**
 * @param {import('../../evals/lib/context.mjs').EvalContext} ctx
 * @param {ReturnType<typeof import('./ai-docs.mjs').buildManifest>} manifest
 */
function renderPatternTypesRaw(ctx, manifest) {
	const blocks = [];
	for (const p of ctx.inventory.patterns) {
		const component = manifest.components[p.name];
		const e = expectationsFor(ctx, p);
		// platform inputs are PascalCase; lower-case public fields (rangeSliderMode, …) are provider internals
		const props = [...e.props].filter(
			(x) => x.kind !== 'function' && !INTERNAL_CALLBACK.test(x.typeText ?? '') && /^[A-Z]/.test(x.name)
		);
		const lines = [
			'// eslint-disable-next-line @typescript-eslint/no-unused-vars',
			`namespace OutSystems.OSUI.Patterns.${p.name}API {`,
			'\t/**',
			`\t * Configuration accepted by ${p.name}API.Create, as an object or as its JSON string.`,
			`\t * Generated by ${GENERATOR} from the ${p.name} configuration classes — do not edit.`,
			'\t */',
			'\texport type Configs = {',
		];
		// members alphabetically, including the shared ExtendedClass (member-ordering lint rule)
		const members = props.map((prop) => {
			const described = component.props[prop.name];
			const { type, note } = publicType(ctx, p, described?.type ?? 'unknown', prop);
			const doc = [described?.description, described?.hint ? `(${described.hint})` : '', note]
				.filter(Boolean)
				.join(' ');
			return { name: prop.name, type, doc };
		});
		members.push({
			name: 'ExtendedClass',
			type: 'string',
			doc: 'Extra CSS classes applied to the pattern root element.',
		});
		// code-point order, which is what the member-ordering lint rule ("alphabetically") checks
		members.sort((a, b) => codePointCompare(a.name, b.name));
		for (const m of members) {
			if (m.doc) lines.push(`\t\t${jsdocLine(m.doc)}`);
			lines.push(`\t\t${m.name}?: ${m.type};`);
		}
		const events = [
			...new Set([...e.events, 'Initialized', ...(p.providerDirs.length ? ['OnProviderConfigsApplied'] : [])]),
		];
		const eventUnion = events.map((ev) => `'${ev}'`).join(' | ');
		lines.push(
			'\t};',
			'',
			'\t/** Event names understood by RegisterCallback; any other string is passed through unchanged. */',
			`\texport type EventName = ${eventUnion} | (string & {});`,
			'}'
		);
		blocks.push(lines.join('\n'));
	}
	return `${[
		'/*',
		' * GENERATED FILE — do not edit by hand.',
		` * Source: the pattern configuration classes and event enums, via ${GENERATOR} (npm run types:generate).`,
		" * Each block merges into the pattern's public API namespace and is emitted into the published .d.ts.",
		' */',
		'',
		blocks.join('\n\n'),
	].join('\n')}\n`;
}
