// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace Providers.Datepicker.Flatpickr {
	/*
	 * List of all available library options.
	 **/
	export const options = {
		altFormat: undefined,
		altInput: undefined,
		altInputClass: undefined,
		allowInput: undefined,
		allowInvalidPreload: undefined,
		appendTo: undefined,
		ariaDateFormat: undefined,
		conjunction: undefined,
		clickOpens: undefined,
		dateFormat: undefined,
		defaultDate: undefined,
		defaultHour: undefined,
		defaultMinute: undefined,
		disable: undefined,
		disableMobile: undefined,
		enable: undefined,
		enableTime: undefined,
		enableSeconds: undefined,
		formatDate: undefined,
		hourIncrement: undefined,
		inline: undefined,
		maxDate: undefined,
		minDate: undefined,
		minuteIncrement: undefined,
		mode: undefined,
		nextArrow: undefined,
		noCalendar: undefined,
		onChange: undefined,
		onClose: undefined,
		onOpen: undefined,
		onReady: undefined,
		parseDate: undefined,
		position: undefined,
		positionElement: undefined,
		prevArrow: undefined,
		shorthandCurrentMonth: undefined,
		static: undefined,
		showMonths: undefined,
		time_24hr: undefined,
		weekNumbers: undefined,
		wrap: undefined,
		monthSelectorType: undefined,
	};
}
