name: docs-generate-deploy-manually

on:
    workflow_dispatch:

jobs:
    compile-prod:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main

            - run: npm install

            - name: Compile Prod
              run: npm run build

            - name: Git Commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: Compiled Production Mode [skip ci]

    update-doc:
        needs: compile-prod
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main
                  token: ${{ secrets.PAT }}

            - uses: actions/setup-node@v3

            - run: npm install

            - name: Install graphviz
              run: sudo apt install -y graphviz

            - run: npm run docs

            - name: Git Commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: Update documentation [skip ci]

    deploy-doc:
        needs: update-doc
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main

            - uses: actions/setup-node@v3

            - name: Push files into github page
              uses: GuillaumeFalourd/copy-push-files@v1

              with:
                  source_files: docs/*
                  remote_repository: https://github.com/outsystems-ui-docs/outsystems-ui-docs.github.io
                  access_token: ${{ secrets.UICOMPONENTSDOCS }}
                  target_branch: main
                  commit_message: Deploy documentation.
