name: ManageDocs

on:
    workflow_call:
        inputs:
            branch-name:
                description: 'Branch to be used as base to create a new one to generate and be published.'
                type: string
                required: true
            delete-created-branch:
                description: 'When True deploy-docs branch will be removed at the end of process.'
                type: boolean
                required: true
            run-lint:
                description: 'Compile and perform lint tests to ensure there is no issues at given branch name.'
                type: boolean
                default: true

jobs:
    check-repo:
        runs-on: ubuntu-latest

        outputs:
            is-real-osui-repo: ${{ steps.check-is-real-osui-repo.outputs.isIt }}

        steps:
            - name: Check if it's outsystems-ui real repository
              id: check-is-real-osui-repo
              run: |
                  echo "isIt=${{ github.event.repository.name == 'outsystems-ui' }}" >> "$GITHUB_OUTPUT"

    run-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into ${{ inputs.branch-name }}
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.branch-name }}
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Install project dependencies
              if: ${{ inputs.run-lint == true }}
              run: npm install

            - name: Run build
              if: ${{ inputs.run-lint == true }}
              run: npm run build

    create-branch:
        needs: run-lint
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into ${{ inputs.branch-name }}
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.branch-name }}
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Create new deploy-docs branch based on ${{ inputs.branch-name }}
              run: |
                  git checkout -b deploy-docs
                  git push -u origin deploy-docs

    create-doc:
        needs: create-branch
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Configure Git with the UiComponentsBot Token
              run: |
                  git config --global user.email "sa_git_uicomponents@outsystems.com"
                  git config --global user.name "UiComponentsBot"

            - name: Checkout into deploy-docs
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: deploy-docs
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Install project dependencies
              run: npm install

            - name: Install graphviz
              run: sudo apt install -y graphviz

            - name: Generate documentation
              run: npm run docs

            - name: Perform git commit
              uses: ./.github/os-git-actions/manual-commit/
              with:
                  branch: deploy-docs
                  message: 'Update documentation [skip ci]'
                  newFiles: true

    publish-doc:
        needs: [check-repo, create-doc]
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into deploy-docs
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: deploy-docs
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Get osuidocs Token
              id: get-osuidocs-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-osuidocs-token-prd

            - name: Push documentation files into github page
              if: ${{ needs.check-repo.outputs.is-real-osui-repo == 'true' }}
              uses: GuillaumeFalourd/copy-push-files@758ee05c45fbd682b62908f2373bf070077a1e43 # v1
              with:
                  source_files: docs/*
                  remote_repository: https://github.com/outsystems-ui-docs/outsystems-ui-docs.github.io
                  access_token: ${{ steps.get-osuidocs-token.outputs.az-keyvault-value }}
                  target_branch: main
                  commit_message: Deploy documentation.

    delete-branch:
        needs: publish-doc
        runs-on: ubuntu-latest

        if: ${{ inputs.delete-created-branch == true }}
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: dev

            - name: Delete branch deploy-docs
              shell: bash
              run: |
                  git push origin -d deploy-docs
