name: ManageNPM

on:
    workflow_call:
        inputs:
            branch-name:
                description: 'Branch to be used as base to create a new one and be published.'
                type: string
                required: true
            delete-created-branch:
                description: 'When True deploy-npm branch will be removed at the end of process.'
                type: boolean
                required: true
            run-lint:
                description: 'Compile and perform lint tests to ensure there is no issues at given branch name.'
                type: boolean
                default: true

jobs:
    check-repo:
        runs-on: ubuntu-latest

        outputs:
            is-real-osui-repo: ${{ steps.check-is-real-osui-repo.outputs.isIt }}

        steps:
            - name: Check if it's outsystems-ui real repository
              id: check-is-real-osui-repo
              run: |
                  echo "isIt=${{ github.event.repository.name == 'outsystems-ui' }}" >> "$GITHUB_OUTPUT"

    run-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into ${{ inputs.branch-name }}
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.branch-name }}
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Install project dependencies
              if: ${{ inputs.run-lint == true }}
              run: |
                  npm install

            - name: Run build
              if: ${{ inputs.run-lint == true }}
              run: |
                  npm run build

    create-branch:
        needs: run-lint
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into ${{ inputs.branch-name }}
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.branch-name }}
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Create new deploy-npm branch based on ${{ inputs.branch-name }}
              run: |
                  git checkout -b deploy-npm
                  git push -u origin deploy-npm

    prepare-branch:
        needs: create-branch
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Configure Git with the UiComponentsBot Token
              run: |
                  git config --global user.email "sa_git_uicomponents@outsystems.com"
                  git config --global user.name "UiComponentsBot"

            - name: Checkout into deploy-npm
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: deploy-npm
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - name: Install project dependencies
              run: |
                  npm install

            - name: Remove dist folder from .gitignore
              run: |
                  gulp removeDistFromGitIgnore

            - name: Compile into production mode
              run: |
                  npm run build

            - name: Clean files and folders
              run: |
                  gulp prepareToDeploy

            - name: Commit, remove gitignore and commit again!
              run: |
                  git add .
                  git commit -m 'OK to Deploy into NPM. [skip ci]'
                  git push origin deploy-npm

                  rm .gitignore

                  git add .
                  git commit -m 'OK to Deploy into NPM. [skip ci]'
                  git push origin deploy-npm

    publish-npm:
        needs: [check-repo, prepare-branch]
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7

            - name: Get GitHub Token
              id: get-github-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-gitpersonal-token-prd

            - name: Checkout into deploy-npm
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: deploy-npm
                  token: ${{ steps.get-github-token.outputs.az-keyvault-value }}

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: Get NPM Token
              id: get-npm-token
              uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              with:
                  key-name: o11odc-github-npm-token-prd

            - name: Publish new version to NPM
              if: ${{ needs.check-repo.outputs.is-real-osui-repo == 'true' }}
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ steps.get-npm-token.outputs.az-keyvault-value }}

    delete-branch:
        needs: publish-npm
        runs-on: ubuntu-latest

        if: ${{ inputs.delete-created-branch == true }}
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: dev

            - name: Delete branch deploy-npm
              shell: bash
              run: |
                  git push origin -d deploy-npm
