name: npm-deploy-manually

on:
    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch main
              uses: actions/checkout@v3
              with:
                  ref: main

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: Publish new version to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_UICOMPONENTS}}
