name: release-npm-manually

on:
    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_UICOMPONENTS}}
