name: Validate pull request title

on:
    pull_request:
        types: [opened, reopened, edited]

jobs:
    build:
        uses: OutSystems/rd.github-reusable-workflows/.github/workflows/validate-pr-title.yaml@v2.0.2
        with:
            validate-semVer: false
